[mypy]
python_version = 3.13
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_defs = false
no_implicit_optional = false
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
explicit_package_bases = true
disable_error_code = call-arg, attr-defined, union-attr, assignment, arg-type, var-annotated, misc, no-any-return, operator, call-overload, dict-item, no-redef, has-type
exclude = venv|__pycache__|\.pytest_cache
