line-length = 120

[lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "B",
    "UP",
    "SIM",
    "RUF",
]
ignore = [
    "B007",
    "B008",
    "B904",
    "B905",
    "E402",
    "E701",
    "E711",
    "E712",
    "E501",
    "E741",
    "F841",
    "RUF006",
    "RUF046",
    "RUF059",
    "SIM102",
    "SIM105",
    "SIM108",
    "SIM117",
    "W291",
]

[format]
