# ==============================================================================
# Tech News Today - RC4 Data Pipeline & Stack Status Inspector (status.ps1)
# ==============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $scriptDir "common.ps1")

$config = Get-DevConfig
Show-VersionBanner -Config $config -ActiveMode "STATUS"

Write-Host "==============================================================================" -ForegroundColor DarkCyan
Write-Host " LIVE DATA STACK & PIPELINE TELEMETRY" -ForegroundColor Cyan
Write-Host "==============================================================================" -ForegroundColor DarkCyan

$runtimeUrl = "http://localhost:$($config.ports.backend)$($config.healthCheckEndpoints.runtime)"
$cqrsUrl    = "http://localhost:$($config.ports.backend)$($config.healthCheckEndpoints.cqrs)"

$runtimeRes = Invoke-HealthEndpoint -Url $runtimeUrl
$cqrsRes    = Invoke-HealthEndpoint -Url $cqrsUrl

if (-not $runtimeRes.Success) {
    Write-ToolkitError "Backend API gateway unreachable at $runtimeUrl."
    Write-ToolkitError "Ensure the stack is started using 'start.bat full'."
    exit $script:EXIT_FATAL_ERROR
}

$rtData   = $runtimeRes.Data.data
$cqrsData = if ($cqrsRes.Success) { $cqrsRes.Data.data } else { $null }

# Infrastructure
Write-Host "`n[INFRASTRUCTURE TELEMETRY]" -ForegroundColor Gray
Write-Host "  PostgreSQL Latency ... $($rtData.postgres.latency_ms) ms" -ForegroundColor Green
Write-Host "  Redis Latency ........ $($rtData.redis.latency_ms) ms (Queue Depth: $($rtData.redis.queue_depth))" -ForegroundColor Green
Write-Host "  pgvector Extension ... $($rtData.pgvector)" -ForegroundColor Green

# Workers
Write-Host "`n[ASYNCHRONOUS WORKER TELEMETRY]" -ForegroundColor Gray
Write-Host "  Workers Online ....... $($rtData.celery.workers_online)" -ForegroundColor Green
Write-Host "  Beat Status .......... $($rtData.celery.beat.status) (Heartbeat age: $($rtData.celery.beat.age_seconds)s)" -ForegroundColor Green
Write-Host "  AI Queue Depth ....... $($rtData.ai_queue_depth) jobs queued" -ForegroundColor Green

# CQRS Data Stack Metrics
Write-Host "`n[CQRS DATA STACK METRICS]" -ForegroundColor Gray
if ($cqrsData) {
    $lagColor   = if ($cqrsData.projection_lag -eq 0) { "Green" } else { "Yellow" }
    $sumColor   = if ($cqrsData.missing_summaries -eq 0) { "Green" } else { "Yellow" }
    $thumbColor = if ($cqrsData.missing_thumbnails -eq 0) { "Green" } else { "Yellow" }

    Write-Host "  Processed Articles ... $($cqrsData.processed_articles)" -ForegroundColor Green
    Write-Host "  Read Model Articles .. $($cqrsData.read_model_articles) (Sync Rate: $($cqrsData.projection_success_rate))" -ForegroundColor Green
    Write-Host "  Projection Lag ....... $($cqrsData.projection_lag) events pending" -ForegroundColor $lagColor
    Write-Host "  Outbox Backlog ....... $($cqrsData.outbox_backlog)" -ForegroundColor Green
    Write-Host "  Missing Summaries .... $($cqrsData.missing_summaries)" -ForegroundColor $sumColor
    Write-Host "  Missing Thumbnails ... $($cqrsData.missing_thumbnails)" -ForegroundColor $thumbColor
} else {
    Write-ToolkitWarn "CQRS endpoint telemetry currently unavailable."
}

# Projection Inspector
Write-Host "`n[HOMEPAGE PROJECTION INSPECTOR]" -ForegroundColor Gray
try {
    $projOutput = docker compose exec -T db psql -U postgres -d tech_news_today -t -c "SELECT projection_version, ranking_version, pipeline_version, generated_by, jsonb_array_length(stories_json), created_at FROM homepage_projections ORDER BY created_at DESC LIMIT 1;" 2>$null
    if ($projOutput -and $projOutput.Trim()) {
        $parts = $projOutput.Trim() -split '\|'
        if ($parts.Count -ge 6) {
            Write-Host "  Latest Projection .... v$($parts[0].Trim()) (Ranking: $($parts[1].Trim()), Pipeline: $($parts[2].Trim()))" -ForegroundColor Green
            Write-Host "  Generated By ......... $($parts[3].Trim()) at $($parts[5].Trim())" -ForegroundColor Green
            Write-Host "  Stories Count ........ $($parts[4].Trim()) active stories" -ForegroundColor Green
        } else {
            Write-Host "  Latest Projection .... Initializing..." -ForegroundColor Yellow
        }
    } else {
        Write-Host "  Latest Projection .... Pending first build" -ForegroundColor Yellow
    }
} catch {
    Write-ToolkitWarn "Projection telemetry currently unavailable."
}

Write-Host "`n==============================================================================" -ForegroundColor DarkCyan
Write-ToolkitSuccess "Status inspection complete."
exit $script:EXIT_SUCCESS
