const { execSync } = require('child_process');
const fs = require('fs');

console.log("=== Running Phase 6I Part 2: Operational Excellence Certification ===\n");

function runCommand(command: string, name: string): string {
  console.log(`[ ] Running ${name}...`);
  try {
    const output = execSync(command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    console.log(`[✔] ${name} passed.\n`);
    return output;
  } catch (error: any) {
    console.error(`[X] ${name} failed. Aborting certification.\n`);
    if (error.stdout) console.log(error.stdout);
    if (error.stderr) console.error(error.stderr);
    process.exit(1);
  }
}

function checkFileExists(path: string, name: string) {
  if (fs.existsSync(path)) {
    console.log(`[✔] Found ${name}: ${path}`);
  } else {
    console.error(`[X] Missing ${name}: ${path}`);
    process.exit(1);
  }
}

function checkCommandRegistry() {
  console.log("[ ] Validating Command Registry...");
  const registryPath = 'src/lib/commands/registry.tsx';
  if (!fs.existsSync(registryPath)) {
    console.error(`[X] Missing Command Registry: ${registryPath}`);
    process.exit(1);
  }
  
  const content = fs.readFileSync(registryPath, 'utf8');
  
  const idMatches = [...content.matchAll(/id:\s*["']([^"']+)["']/g)];
  const ids = idMatches.map(m => m[1]);
  const duplicateIds = ids.filter((item, index) => ids.indexOf(item) !== index);
  if (duplicateIds.length > 0) {
    console.error(`[X] Found duplicate Command IDs: ${duplicateIds.join(', ')}`);
    process.exit(1);
  }

  const shortcutMatches = [...content.matchAll(/shortcut:\s*\[(["'][^"']+["']\s*(?:,\s*["'][^"']+["'])*)\]/g)];
  const shortcuts = shortcutMatches.map(m => m[1].replace(/["']/g, '').trim());
  const duplicateShortcuts = shortcuts.filter((item, index) => shortcuts.indexOf(item) !== index);
  if (duplicateShortcuts.length > 0) {
    console.error(`[X] Found duplicate Command Shortcuts: ${duplicateShortcuts.join(', ')}`);
    process.exit(1);
  }

  console.log(`[✔] Command Registry Validated. Found ${ids.length} unique commands.`);
}

console.log("1. Checking Required Providers & Configuration...");
checkFileExists('src/components/providers/TelemetryProvider.tsx', 'Telemetry Provider');
checkFileExists('src/components/providers/ErrorProvider.tsx', 'Error Provider');
checkFileExists('src/components/providers/PerformanceProvider.tsx', 'Performance Provider');
checkFileExists('src/components/providers/InstallProvider.tsx', 'Install Provider');
checkFileExists('src/lib/error/adapters/SentryAdapter.ts', 'Sentry Error Adapter');
checkFileExists('src/lib/error/adapters/CustomBackendAdapter.ts', 'Backend Error Adapter');
checkFileExists('src/config/build.ts', 'Build Metadata');
checkFileExists('src/app/~offline/page.tsx', 'Offline Page');
checkFileExists('public/manifest.json', 'PWA Manifest');
checkFileExists('public/icon-192.png', 'PWA Icons');

console.log("\n2. Checking Architecture Requirements...");
checkCommandRegistry();

console.log("\n3. Running Typecheck...");
runCommand('npm run typecheck', 'TypeScript Compilation');

console.log("\n4. Running Linter...");
runCommand('npm run lint', 'ESLint');

console.log("\n5. Checking Build and Bundle Sizes...");
const buildOutput = runCommand('npm run build', 'Next.js Build');

// PWA Verification
checkFileExists('public/sw.js', 'Service Worker (Generated by Build)');

// Bundle Intelligence Configuration (in KB)
const bundleBudgets: Record<string, number> = {
  "/": 200,
  "/articles/[slug]": 250,
  "/dashboard": 250,
  "/search": 250
};

console.log("\n6. Validating Bundle Budgets...");
const lines = buildOutput.split('\n');
let budgetFailed = false;

for (const line of lines) {
  // Typical output line: "○ /   184 B   180 kB" or "ƒ /search   0 B   180 kB"
  // We want to capture the route and the "First Load JS" size (which is usually the last column)
  const match = line.match(/(?:○|ƒ|●|λ)\s+(.+?)\s+(?:\d+(?:\.\d+)?\s+[a-zA-Z]+)\s+(\d+(?:\.\d+)?)\s+([a-zA-Z]+)/);
  if (match) {
    const route = match[1].trim();
    const size = parseFloat(match[2]);
    const unit = match[3].toLowerCase();
    
    // Normalize size to KB
    let sizeInKb = size;
    if (unit === 'mb') sizeInKb = size * 1024;
    else if (unit === 'b') sizeInKb = size / 1024;

    // Check against budgets
    if (bundleBudgets[route]) {
      const budget = bundleBudgets[route];
      if (sizeInKb > budget) {
        console.error(`[X] Bundle Budget Exceeded: ${route} is ${sizeInKb.toFixed(2)} KB (Limit: ${budget} KB)`);
        budgetFailed = true;
      } else {
        console.log(`[✔] ${route}: ${sizeInKb.toFixed(2)} KB (Limit: ${budget} KB)`);
      }
    }
  }
}

if (budgetFailed) {
  console.error(`\n[X] Bundle Size Check Failed. Please optimize dependencies.`);
  process.exit(1);
}

console.log("\n=== Phase 6I Part 2 Certification Passed! ===");
console.log("Operational Excellence standards achieved.");

export {};

export {};
