-- BEGIN GENERATED SCHEMA
-- Generated by generate_schema.py
-- Schema Revision: b6b59202870b
-- Generated: 2026-06-11T10:09:42.743742+00:00Z

--
-- PostgreSQL database dump
--

\restrict IXI2cMaUdQDUstbMfwufK2RJPzICVQ5ItLhQlw1c5JoPbT18EZ7NUjDPzmWEXEx


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agent_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_logs (
    id integer NOT NULL,
    agent_name character varying(100) NOT NULL,
    action character varying(255) NOT NULL,
    details text,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: agent_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.agent_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: agent_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.agent_logs_id_seq OWNED BY public.agent_logs.id;


--
-- Name: ai_job_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_job_history (
    id integer NOT NULL,
    raw_article_id integer,
    processed_article_id integer,
    model character varying(100) NOT NULL,
    prompt_tokens integer NOT NULL,
    completion_tokens integer NOT NULL,
    cost numeric(10,6) NOT NULL,
    latency_ms integer NOT NULL,
    status character varying(50) NOT NULL,
    error_message text,
    created_at timestamp with time zone NOT NULL,
    provider character varying(50) DEFAULT 'disabled'::character varying NOT NULL,
    task_type character varying(50),
    prompt_version character varying(50),
    total_tokens integer DEFAULT 0 NOT NULL,
    cost_usd numeric(10,6) DEFAULT '0'::numeric NOT NULL,
    cache_hit boolean DEFAULT false NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    error text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    provider_metadata json DEFAULT '{}'::json NOT NULL,
    enrichment_input_fingerprint character varying(64),
    prompt_hash character varying(64)
);


--
-- Name: ai_job_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ai_job_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ai_job_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ai_job_history_id_seq OWNED BY public.ai_job_history.id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: article_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_revisions (
    id integer NOT NULL,
    article_id integer NOT NULL,
    user_id integer,
    title character varying(255) NOT NULL,
    summary text NOT NULL,
    tags text,
    content text NOT NULL,
    revision_number integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: article_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.article_revisions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: article_revisions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.article_revisions_id_seq OWNED BY public.article_revisions.id;


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id integer NOT NULL,
    user_id integer,
    action character varying(255) NOT NULL,
    resource character varying(255),
    metadata json NOT NULL,
    ip_address character varying(45),
    device text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_logs_id_seq OWNED BY public.audit_logs.id;


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.categories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- Name: feature_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feature_flags (
    id integer NOT NULL,
    key character varying(100) NOT NULL,
    value boolean NOT NULL,
    description text,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: feature_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.feature_flags_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: feature_flags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.feature_flags_id_seq OWNED BY public.feature_flags.id;


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    message text,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;


--
-- Name: oauth_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_accounts (
    id integer NOT NULL,
    user_id integer NOT NULL,
    provider character varying(50) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: oauth_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.oauth_accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: oauth_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.oauth_accounts_id_seq OWNED BY public.oauth_accounts.id;


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.permissions_id_seq OWNED BY public.permissions.id;


--
-- Name: processed_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_articles (
    id integer NOT NULL,
    raw_article_id integer,
    source_id integer,
    category_id integer NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    summary text NOT NULL,
    content text NOT NULL,
    image_url character varying,
    source character varying(150) NOT NULL,
    hero_image character varying,
    source_name character varying(150) NOT NULL,
    source_url character varying,
    clean_html text,
    tags text,
    ai_confidence numeric NOT NULL,
    reading_time integer NOT NULL,
    published_status character varying(50) NOT NULL,
    tokens_used integer NOT NULL,
    seo_title character varying(255),
    seo_keywords text,
    readability_score integer,
    created_at timestamp with time zone NOT NULL,
    published_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    is_archived boolean NOT NULL,
    impact_score numeric NOT NULL,
    freshness_score numeric NOT NULL,
    engagement_score numeric NOT NULL,
    final_score numeric NOT NULL,
    thumbnail_url text,
    thumbnail_local text,
    thumbnail_status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    thumbnail_hash character varying(64),
    thumbnail_source character varying(50),
    thumbnail_quality_score integer,
    candidate_count integer DEFAULT 0,
    winner_pass character varying,
    selected_score integer,
    sentiment character varying(20),
    embedding_status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    embedding public.vector(1536),
    embedding_hash character varying(64),
    embedding_updated_at timestamp with time zone,
    cluster_id character varying(36),
    cluster_score numeric,
    cluster_updated_at timestamp with time zone
);


--
-- Name: processed_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.processed_articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: processed_articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.processed_articles_id_seq OWNED BY public.processed_articles.id;


--
-- Name: raw_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_articles (
    id integer NOT NULL,
    source_id integer,
    title character varying(255) NOT NULL,
    url character varying NOT NULL,
    url_hash character varying(64) NOT NULL,
    title_hash character varying(64) NOT NULL,
    compressed_html bytea,
    clean_text text,
    article_metadata text,
    parser_version character varying(50) NOT NULL,
    scraped_at timestamp with time zone NOT NULL,
    status character varying(50) NOT NULL,
    retry_count integer NOT NULL,
    error_log text,
    processed_at timestamp with time zone,
    html_refetched_at timestamp with time zone,
    last_retry_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    dead_letter_reason text,
    dead_letter_at timestamp with time zone
);


--
-- Name: raw_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.raw_articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: raw_articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.raw_articles_id_seq OWNED BY public.raw_articles.id;


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    role_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- Name: saved_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_articles (
    id integer NOT NULL,
    user_id integer NOT NULL,
    article_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: saved_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.saved_articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: saved_articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.saved_articles_id_seq OWNED BY public.saved_articles.id;


--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(50) NOT NULL,
    method character varying(50) NOT NULL,
    url character varying NOT NULL,
    credibility_score integer NOT NULL,
    crawl_interval integer NOT NULL,
    enabled boolean NOT NULL,
    health_state character varying(50) NOT NULL,
    failure_count integer NOT NULL,
    last_crawl_at timestamp with time zone,
    parser_version character varying(50) NOT NULL,
    parser_config character varying,
    total_crawls integer NOT NULL,
    successful_crawls integer NOT NULL,
    reliability_score numeric NOT NULL,
    last_failure_type character varying(100),
    created_at timestamp with time zone NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL
);


--
-- Name: sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sources_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sources_id_seq OWNED BY public.sources.id;


--
-- Name: thumbnail_decision_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.thumbnail_decision_log (
    id integer NOT NULL,
    article_id integer NOT NULL,
    candidate_url character varying NOT NULL,
    source character varying NOT NULL,
    accepted boolean,
    rejection_reason character varying,
    width integer,
    height integer,
    aspect_ratio double precision,
    created_at timestamp with time zone
);


--
-- Name: thumbnail_decision_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.thumbnail_decision_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: thumbnail_decision_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.thumbnail_decision_log_id_seq OWNED BY public.thumbnail_decision_log.id;


--
-- Name: topic_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topic_aliases (
    id integer NOT NULL,
    topic_id integer NOT NULL,
    alias character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: topic_aliases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.topic_aliases_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: topic_aliases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.topic_aliases_id_seq OWNED BY public.topic_aliases.id;


--
-- Name: topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topics (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(50),
    description text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.topics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: topics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.topics_id_seq OWNED BY public.topics.id;


--
-- Name: trending_topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trending_topics (
    id integer NOT NULL,
    topic character varying(100) NOT NULL,
    weight integer NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: trending_topics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trending_topics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trending_topics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trending_topics_id_seq OWNED BY public.trending_topics.id;


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    refresh_token character varying(512) NOT NULL,
    ip_address character varying(45),
    device text,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason character varying(100),
    created_at timestamp with time zone NOT NULL
);


--
-- Name: user_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_sessions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_sessions_id_seq OWNED BY public.user_sessions.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    given_name character varying(100),
    family_name character varying(100),
    profile_picture text,
    role_id integer,
    status character varying(50) NOT NULL,
    last_login timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: agent_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_logs ALTER COLUMN id SET DEFAULT nextval('public.agent_logs_id_seq'::regclass);


--
-- Name: ai_job_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_job_history ALTER COLUMN id SET DEFAULT nextval('public.ai_job_history_id_seq'::regclass);


--
-- Name: article_revisions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_revisions ALTER COLUMN id SET DEFAULT nextval('public.article_revisions_id_seq'::regclass);


--
-- Name: audit_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs ALTER COLUMN id SET DEFAULT nextval('public.audit_logs_id_seq'::regclass);


--
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- Name: feature_flags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_flags ALTER COLUMN id SET DEFAULT nextval('public.feature_flags_id_seq'::regclass);


--
-- Name: notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);


--
-- Name: oauth_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts ALTER COLUMN id SET DEFAULT nextval('public.oauth_accounts_id_seq'::regclass);


--
-- Name: permissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions ALTER COLUMN id SET DEFAULT nextval('public.permissions_id_seq'::regclass);


--
-- Name: processed_articles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_articles ALTER COLUMN id SET DEFAULT nextval('public.processed_articles_id_seq'::regclass);


--
-- Name: raw_articles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_articles ALTER COLUMN id SET DEFAULT nextval('public.raw_articles_id_seq'::regclass);


--
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- Name: saved_articles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_articles ALTER COLUMN id SET DEFAULT nextval('public.saved_articles_id_seq'::regclass);


--
-- Name: sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources ALTER COLUMN id SET DEFAULT nextval('public.sources_id_seq'::regclass);


--
-- Name: thumbnail_decision_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thumbnail_decision_log ALTER COLUMN id SET DEFAULT nextval('public.thumbnail_decision_log_id_seq'::regclass);


--
-- Name: topic_aliases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_aliases ALTER COLUMN id SET DEFAULT nextval('public.topic_aliases_id_seq'::regclass);


--
-- Name: topics id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics ALTER COLUMN id SET DEFAULT nextval('public.topics_id_seq'::regclass);


--
-- Name: trending_topics id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trending_topics ALTER COLUMN id SET DEFAULT nextval('public.trending_topics_id_seq'::regclass);


--
-- Name: user_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions ALTER COLUMN id SET DEFAULT nextval('public.user_sessions_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: agent_logs agent_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_logs
    ADD CONSTRAINT agent_logs_pkey PRIMARY KEY (id);


--
-- Name: ai_job_history ai_job_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_job_history
    ADD CONSTRAINT ai_job_history_pkey PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: article_revisions article_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_revisions
    ADD CONSTRAINT article_revisions_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: categories categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_slug_key UNIQUE (slug);


--
-- Name: feature_flags feature_flags_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_key_key UNIQUE (key);


--
-- Name: feature_flags feature_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: oauth_accounts oauth_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: processed_articles processed_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_articles
    ADD CONSTRAINT processed_articles_pkey PRIMARY KEY (id);


--
-- Name: raw_articles raw_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_articles
    ADD CONSTRAINT raw_articles_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: saved_articles saved_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_articles
    ADD CONSTRAINT saved_articles_pkey PRIMARY KEY (id);


--
-- Name: sources sources_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_name_key UNIQUE (name);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: sources sources_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_url_key UNIQUE (url);


--
-- Name: thumbnail_decision_log thumbnail_decision_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thumbnail_decision_log
    ADD CONSTRAINT thumbnail_decision_log_pkey PRIMARY KEY (id);


--
-- Name: topic_aliases topic_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_aliases
    ADD CONSTRAINT topic_aliases_pkey PRIMARY KEY (id);


--
-- Name: topics topics_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_name_key UNIQUE (name);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: trending_topics trending_topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trending_topics
    ADD CONSTRAINT trending_topics_pkey PRIMARY KEY (id);


--
-- Name: trending_topics trending_topics_topic_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trending_topics
    ADD CONSTRAINT trending_topics_topic_key UNIQUE (topic);


--
-- Name: oauth_accounts unique_provider_sub; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT unique_provider_sub UNIQUE (provider, provider_user_id);


--
-- Name: oauth_accounts unique_user_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT unique_user_provider UNIQUE (user_id, provider);


--
-- Name: raw_articles uq_url_title_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_articles
    ADD CONSTRAINT uq_url_title_hash UNIQUE (url_hash, title_hash);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ix_agent_logs_agent_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_agent_logs_agent_name ON public.agent_logs USING btree (agent_name);


--
-- Name: ix_agent_logs_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_agent_logs_id ON public.agent_logs USING btree (id);


--
-- Name: ix_ai_job_history_enrichment_input_fingerprint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_enrichment_input_fingerprint ON public.ai_job_history USING btree (enrichment_input_fingerprint);


--
-- Name: ix_ai_job_history_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_id ON public.ai_job_history USING btree (id);


--
-- Name: ix_ai_job_history_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_model ON public.ai_job_history USING btree (model);


--
-- Name: ix_ai_job_history_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_provider ON public.ai_job_history USING btree (provider);


--
-- Name: ix_ai_job_history_raw_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_raw_article_id ON public.ai_job_history USING btree (raw_article_id);


--
-- Name: ix_ai_job_history_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_status ON public.ai_job_history USING btree (status);


--
-- Name: ix_ai_job_history_task_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_job_history_task_type ON public.ai_job_history USING btree (task_type);


--
-- Name: ix_article_revisions_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_article_revisions_article_id ON public.article_revisions USING btree (article_id);


--
-- Name: ix_article_revisions_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_article_revisions_id ON public.article_revisions USING btree (id);


--
-- Name: ix_article_revisions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_article_revisions_user_id ON public.article_revisions USING btree (user_id);


--
-- Name: ix_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_logs_action ON public.audit_logs USING btree (action);


--
-- Name: ix_audit_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_logs_created_at ON public.audit_logs USING btree (created_at);


--
-- Name: ix_audit_logs_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_logs_id ON public.audit_logs USING btree (id);


--
-- Name: ix_audit_logs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_logs_user_id ON public.audit_logs USING btree (user_id);


--
-- Name: ix_categories_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_categories_id ON public.categories USING btree (id);


--
-- Name: ix_feature_flags_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_feature_flags_id ON public.feature_flags USING btree (id);


--
-- Name: ix_notifications_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_id ON public.notifications USING btree (id);


--
-- Name: ix_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_user_id ON public.notifications USING btree (user_id);


--
-- Name: ix_oauth_accounts_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_oauth_accounts_id ON public.oauth_accounts USING btree (id);


--
-- Name: ix_permissions_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_permissions_id ON public.permissions USING btree (id);


--
-- Name: ix_processed_articles_cluster_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_processed_articles_cluster_id ON public.processed_articles USING btree (cluster_id);


--
-- Name: ix_processed_articles_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_processed_articles_embedding ON public.processed_articles USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: ix_processed_articles_embedding_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_processed_articles_embedding_status ON public.processed_articles USING btree (embedding_status);


--
-- Name: ix_processed_articles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_processed_articles_id ON public.processed_articles USING btree (id);


--
-- Name: ix_processed_articles_published_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_processed_articles_published_status ON public.processed_articles USING btree (published_status);


--
-- Name: ix_processed_articles_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_processed_articles_slug ON public.processed_articles USING btree (slug);


--
-- Name: ix_raw_articles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_raw_articles_id ON public.raw_articles USING btree (id);


--
-- Name: ix_raw_articles_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_raw_articles_status ON public.raw_articles USING btree (status);


--
-- Name: ix_raw_articles_title_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_raw_articles_title_hash ON public.raw_articles USING btree (title_hash);


--
-- Name: ix_raw_articles_url_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_raw_articles_url_hash ON public.raw_articles USING btree (url_hash);


--
-- Name: ix_roles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_roles_id ON public.roles USING btree (id);


--
-- Name: ix_saved_articles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_saved_articles_id ON public.saved_articles USING btree (id);


--
-- Name: ix_saved_articles_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_saved_articles_user_id ON public.saved_articles USING btree (user_id);


--
-- Name: ix_sources_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_id ON public.sources USING btree (id);


--
-- Name: ix_thumbnail_decision_log_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_thumbnail_decision_log_article_id ON public.thumbnail_decision_log USING btree (article_id);


--
-- Name: ix_thumbnail_decision_log_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_thumbnail_decision_log_id ON public.thumbnail_decision_log USING btree (id);


--
-- Name: ix_topic_aliases_alias; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_topic_aliases_alias ON public.topic_aliases USING btree (alias);


--
-- Name: ix_topic_aliases_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_topic_aliases_id ON public.topic_aliases USING btree (id);


--
-- Name: ix_topics_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_topics_id ON public.topics USING btree (id);


--
-- Name: ix_trending_topics_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_trending_topics_id ON public.trending_topics USING btree (id);


--
-- Name: ix_user_sessions_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_sessions_id ON public.user_sessions USING btree (id);


--
-- Name: ix_user_sessions_refresh_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_user_sessions_refresh_token ON public.user_sessions USING btree (refresh_token);


--
-- Name: ix_user_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_sessions_user_id ON public.user_sessions USING btree (user_id);


--
-- Name: ix_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);


--
-- Name: ix_users_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_users_id ON public.users USING btree (id);


--
-- Name: ix_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_users_status ON public.users USING btree (status);


--
-- Name: ai_job_history ai_job_history_processed_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_job_history
    ADD CONSTRAINT ai_job_history_processed_article_id_fkey FOREIGN KEY (processed_article_id) REFERENCES public.processed_articles(id) ON DELETE SET NULL;


--
-- Name: ai_job_history ai_job_history_raw_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_job_history
    ADD CONSTRAINT ai_job_history_raw_article_id_fkey FOREIGN KEY (raw_article_id) REFERENCES public.raw_articles(id) ON DELETE SET NULL;


--
-- Name: article_revisions article_revisions_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_revisions
    ADD CONSTRAINT article_revisions_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.processed_articles(id) ON DELETE CASCADE;


--
-- Name: article_revisions article_revisions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_revisions
    ADD CONSTRAINT article_revisions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: audit_logs audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: oauth_accounts oauth_accounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: processed_articles processed_articles_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_articles
    ADD CONSTRAINT processed_articles_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT;


--
-- Name: processed_articles processed_articles_raw_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_articles
    ADD CONSTRAINT processed_articles_raw_article_id_fkey FOREIGN KEY (raw_article_id) REFERENCES public.raw_articles(id) ON DELETE SET NULL;


--
-- Name: processed_articles processed_articles_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_articles
    ADD CONSTRAINT processed_articles_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE SET NULL;


--
-- Name: raw_articles raw_articles_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_articles
    ADD CONSTRAINT raw_articles_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE SET NULL;


--
-- Name: role_permissions role_permissions_permission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: saved_articles saved_articles_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_articles
    ADD CONSTRAINT saved_articles_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.processed_articles(id) ON DELETE CASCADE;


--
-- Name: saved_articles saved_articles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_articles
    ADD CONSTRAINT saved_articles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: thumbnail_decision_log thumbnail_decision_log_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thumbnail_decision_log
    ADD CONSTRAINT thumbnail_decision_log_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.processed_articles(id) ON DELETE CASCADE;


--
-- Name: topic_aliases topic_aliases_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_aliases
    ADD CONSTRAINT topic_aliases_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: user_sessions user_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: users users_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict IXI2cMaUdQDUstbMfwufK2RJPzICVQ5ItLhQlw1c5JoPbT18EZ7NUjDPzmWEXEx
-- END GENERATED SCHEMA

-- ==============================================================================
-- Phase 4: Seed Roles, Permissions, Role-Permission Mappings, Feature Flags
-- ==============================================================================

-- Seed Roles
INSERT INTO roles (name, description) VALUES
('reader', 'Standard reader with article browsing and bookmark capabilities'),
('editor', 'Editorial staff with article review, approval, and content editing privileges'),
('admin', 'Platform administrator with source, trend, telemetry, and user oversight'),
('super_admin', 'Full platform control including infrastructure, emergency actions, and audit visibility')
ON CONFLICT (name) DO NOTHING;

-- Seed Permissions
INSERT INTO permissions (name, description) VALUES
('read_articles', 'View published articles and search'),
('save_bookmarks', 'Save and manage article bookmarks'),
('manage_profile', 'Edit own profile settings'),
('review_articles', 'Review and moderate article drafts'),
('approve_articles', 'Approve articles for publication'),
('reject_articles', 'Reject articles from publication queue'),
('edit_article_content', 'Edit article titles, summaries, tags, and content'),
('manage_sources', 'Enable, disable, and configure crawler sources'),
('force_crawl', 'Trigger immediate source crawl operations'),
('manage_trends', 'Override trend weights, merge, hide, and pin trends'),
('view_telemetry', 'Access real-time operational telemetry dashboards'),
('manage_users', 'View, search, suspend, and reactivate user accounts'),
('promote_users', 'Promote or demote user roles'),
('view_audit_logs', 'Access administrative audit trail'),
('manage_ai_queue', 'Monitor, retry, pause, and resume AI processing jobs'),
('manage_feature_flags', 'Toggle runtime feature flags'),
('emergency_controls', 'Execute emergency ingestion locks, queue clears, and source shutdowns'),
('manage_notifications', 'View and manage system notifications'),
('full_admin', 'Unrestricted platform administration access')
ON CONFLICT (name) DO NOTHING;

-- Seed Role-Permission Mappings
-- Reader permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'reader' AND p.name IN ('read_articles', 'save_bookmarks', 'manage_profile')
ON CONFLICT DO NOTHING;

-- Editor permissions (includes reader + editorial)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'editor' AND p.name IN (
    'read_articles', 'save_bookmarks', 'manage_profile',
    'review_articles', 'approve_articles', 'reject_articles', 'edit_article_content'
)
ON CONFLICT DO NOTHING;

-- Admin permissions (includes editor + operations)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'admin' AND p.name IN (
    'read_articles', 'save_bookmarks', 'manage_profile',
    'review_articles', 'approve_articles', 'reject_articles', 'edit_article_content',
    'manage_sources', 'force_crawl', 'manage_trends', 'view_telemetry',
    'manage_users', 'view_audit_logs', 'manage_ai_queue', 'manage_notifications'
)
ON CONFLICT DO NOTHING;

-- Super Admin permissions (all)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'super_admin'
ON CONFLICT DO NOTHING;

-- Seed Feature Flags
INSERT INTO feature_flags (key, value, description) VALUES
('enable_ai_processing', TRUE, 'Master toggle for AI summarization pipeline'),
('enable_trends', TRUE, 'Master toggle for trend calculation engine'),
('enable_crawling', TRUE, 'Master toggle for automated source crawling'),
('emergency_pause_ingestion', FALSE, 'Emergency kill-switch to halt all ingestion pipelines'),
('enable_google_oauth', TRUE, 'Toggle Google OAuth sign-in availability'),
('enable_registration', TRUE, 'Toggle new user self-registration')
ON CONFLICT (key) DO NOTHING;

-- ==============================================================================
-- Initial Seeding (Categories & 10 Trusted MVP Sources)
-- ==============================================================================
INSERT INTO categories (name, slug) VALUES 
('Artificial Intelligence', 'artificial-intelligence'),
('Robotics', 'robotics'),
('Startups', 'startups'),
('Cybersecurity', 'cybersecurity'),
('Software Development', 'software-development'),
('Space & Science', 'space-science')
ON CONFLICT (name) DO NOTHING;

INSERT INTO sources (name, category, method, url, credibility_score, crawl_interval) VALUES
('OpenAI Blog', 'official', 'rss', 'https://openai.com/news/rss.xml', 98, 900),
('Anthropic News', 'official', 'rss', 'https://www.anthropic.com/news.rss', 98, 900),
('NVIDIA AI Blog', 'official', 'rss', 'https://blogs.nvidia.com/feed/', 98, 1800),
('Google DeepMind', 'official', 'rss', 'https://deepmind.google/blog/feed/basic/', 98, 1800),
('TechCrunch', 'editorial', 'rss', 'https://techcrunch.com/feed/', 92, 600),
('The Verge', 'editorial', 'rss', 'https://www.theverge.com/rss/index.xml', 90, 600),
('Ars Technica', 'editorial', 'rss', 'https://feeds.arstechnica.com/arstechnica/index', 88, 1200),
('Hacker News', 'community', 'api', 'https://hacker-news.firebaseio.com/v0', 85, 300),
('GitHub Trending', 'community', 'scraping', 'https://github.com/trending', 80, 1800),
('Reddit MachineLearning', 'community', 'rss', 'https://www.reddit.com/r/MachineLearning/.rss', 70, 900)
ON CONFLICT (name) DO NOTHING;
