export const FEATURES = {
  AI_CHAT: process.env.NEXT_PUBLIC_FEATURE_AI_CHAT === "true",
  SEMANTIC_SEARCH: process.env.NEXT_PUBLIC_FEATURE_SEMANTIC === "true",
  TOPICS: process.env.NEXT_PUBLIC_FEATURE_TOPICS === "true",
  READING_HISTORY: process.env.NEXT_PUBLIC_FEATURE_READING_HISTORY === "true",
  RECOMMENDATIONS: process.env.NEXT_PUBLIC_FEATURE_RECOMMENDATIONS === "true",
  ACCOUNT_CENTER: process.env.NEXT_PUBLIC_FEATURE_ACCOUNT_CENTER === "true",
};
