"""Add expires_at and update cascade constraints

Revision ID: 09a793a1c42a
Revises: 9f9999999998
Create Date: 2026-08-07 20:33:13.394470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = '09a793a1c42a'
down_revision: Union[str, Sequence[str], None] = '9f9999999998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.drop_index(op.f('idx_homepage_projections_created_at'), table_name='homepage_projections')
    op.drop_table('homepage_projections')
    op.alter_column('articles', 'thumbnail_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # op.alter_column('articles', 'embedding',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
    #            existing_nullable=True)
    # op.create_index('ix_article_read_model_embedding', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    op.drop_constraint(op.f('behavioral_events_article_id_fkey'), 'behavioral_events', type_='foreignkey')
    op.create_foreign_key(None, 'behavioral_events', 'processed_articles', ['article_id'], ['id'], ondelete='SET NULL')
    op.alter_column('processed_articles', 'thumbnail_retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # op.alter_column('processed_articles', 'embedding',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
    #            existing_nullable=True)
    # op.create_index('ix_processed_articles_embedding', 'processed_articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_processed_articles_expires_at'), 'processed_articles', ['expires_at'], unique=False)
    op.drop_column('processed_articles', 'tags')
    op.drop_column('processed_articles', 'clean_html')
    op.drop_index(op.f('idx_raw_articles_title_trgm'), table_name='raw_articles', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('reading_sessions', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('reading_sessions_article_id_fkey'), 'reading_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'reading_sessions', 'processed_articles', ['article_id'], ['id'], ondelete='SET NULL')
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(op.f('saved_articles_article_id_fkey'), 'saved_articles', type_='foreignkey')
    op.create_foreign_key(None, 'saved_articles', 'articles', ['article_id'], ['id'], ondelete='SET NULL')
    # op.alter_column('search_index_nodes', 'embedding',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
    #            existing_nullable=True)
    op.alter_column('user_reading_history', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(op.f('user_reading_history_article_id_fkey'), 'user_reading_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_reading_history', 'articles', ['article_id'], ['id'], ondelete='SET NULL')
    # op.alter_column('workspace_notes', 'embedding',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
    #            existing_nullable=True)
    # op.create_index('ix_workspace_notes_embedding', 'workspace_notes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_notes_embedding', table_name='workspace_notes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('workspace_notes', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'user_reading_history', type_='foreignkey')
    op.create_foreign_key(op.f('user_reading_history_article_id_fkey'), 'user_reading_history', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_reading_history', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('search_index_nodes', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'saved_articles', type_='foreignkey')
    op.create_foreign_key(op.f('saved_articles_article_id_fkey'), 'saved_articles', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(None, 'reading_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('reading_sessions_article_id_fkey'), 'reading_sessions', 'processed_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reading_sessions', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('idx_raw_articles_title_trgm'), 'raw_articles', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('processed_articles', sa.Column('clean_html', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('processed_articles', sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_processed_articles_expires_at'), table_name='processed_articles')
    op.drop_index('ix_processed_articles_embedding', table_name='processed_articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('processed_articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('processed_articles', 'thumbnail_retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'behavioral_events', type_='foreignkey')
    op.create_foreign_key(op.f('behavioral_events_article_id_fkey'), 'behavioral_events', 'processed_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_article_read_model_embedding', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('articles', 'thumbnail_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('homepage_projections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('projection_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stories_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('homepage_projections_pkey'))
    )
    op.create_index(op.f('idx_homepage_projections_created_at'), 'homepage_projections', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
