"""phase_11_sprint_3_final_editorial_architecture

Revision ID: 0cc9d36826bf
Revises: 52332bb3a66b
Create Date: 2026-06-14 19:27:31.263676

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0cc9d36826bf'
down_revision: str | Sequence[str] | None = '52332bb3a66b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=255), nullable=False),
    sa.Column('configuration_version', sa.String(length=50), nullable=True),
    sa.Column('knowledge_version', sa.String(length=50), nullable=True),
    sa.Column('review_version', sa.String(length=50), nullable=True),
    sa.Column('distribution_version', sa.String(length=50), nullable=True),
    sa.Column('distribution_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_records_article_id'), 'publication_records', ['article_id'], unique=False)
    op.create_index(op.f('ix_publication_records_id'), 'publication_records', ['id'], unique=False)
    op.create_table('editorial_discussion_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('anchor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('closed_by', sa.String(length=255), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_discussion_threads_draft_id'), 'editorial_discussion_threads', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_discussion_threads_id'), 'editorial_discussion_threads', ['id'], unique=False)
    op.create_table('editorial_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_sessions_draft_id'), 'editorial_sessions', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_sessions_id'), 'editorial_sessions', ['id'], unique=False)
    op.add_column('editorial_decisions', sa.Column('decision_source', sa.String(length=100), nullable=True))
    op.add_column('editorial_decisions', sa.Column('decision_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_decisions', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_draft_comments', sa.Column('thread_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_editorial_draft_comments_draft_id'), table_name='editorial_draft_comments')
    op.drop_index(op.f('ix_editorial_draft_comments_parent_id'), table_name='editorial_draft_comments')
    op.create_index(op.f('ix_editorial_draft_comments_thread_id'), 'editorial_draft_comments', ['thread_id'], unique=False)
    op.drop_constraint(op.f('editorial_draft_comments_parent_id_fkey'), 'editorial_draft_comments', type_='foreignkey')
    op.drop_constraint(op.f('editorial_draft_comments_draft_id_fkey'), 'editorial_draft_comments', type_='foreignkey')
    op.create_foreign_key(None, 'editorial_draft_comments', 'editorial_discussion_threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_column('editorial_draft_comments', 'parent_id')
    op.drop_column('editorial_draft_comments', 'start_offset')
    op.drop_column('editorial_draft_comments', 'block_id')
    op.drop_column('editorial_draft_comments', 'end_offset')
    op.drop_column('editorial_draft_comments', 'draft_id')
    op.drop_column('editorial_draft_comments', 'resolved')
    op.add_column('editorial_draft_versions', sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_patches', sa.Column('author', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_patches', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('editorial_patches', sa.Column('accepted_by', sa.String(length=255), nullable=True))
    op.alter_column('editorial_patches', 'section_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editorial_patches', 'section_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('editorial_patches', 'accepted_by')
    op.drop_column('editorial_patches', 'accepted_at')
    op.drop_column('editorial_patches', 'author')
    op.drop_column('editorial_draft_versions', 'environment')
    op.add_column('editorial_draft_comments', sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('editorial_draft_comments', sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('editorial_draft_comments', sa.Column('end_offset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('editorial_draft_comments', sa.Column('block_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('editorial_draft_comments', sa.Column('start_offset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('editorial_draft_comments', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'editorial_draft_comments', type_='foreignkey')
    op.create_foreign_key(op.f('editorial_draft_comments_draft_id_fkey'), 'editorial_draft_comments', 'editorial_drafts', ['draft_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('editorial_draft_comments_parent_id_fkey'), 'editorial_draft_comments', 'editorial_draft_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_editorial_draft_comments_thread_id'), table_name='editorial_draft_comments')
    op.create_index(op.f('ix_editorial_draft_comments_parent_id'), 'editorial_draft_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_editorial_draft_comments_draft_id'), 'editorial_draft_comments', ['draft_id'], unique=False)
    op.drop_column('editorial_draft_comments', 'thread_id')
    op.drop_column('editorial_decisions', 'evidence')
    op.drop_column('editorial_decisions', 'decision_metadata')
    op.drop_column('editorial_decisions', 'decision_source')
    op.drop_index(op.f('ix_editorial_sessions_id'), table_name='editorial_sessions')
    op.drop_index(op.f('ix_editorial_sessions_draft_id'), table_name='editorial_sessions')
    op.drop_table('editorial_sessions')
    op.drop_index(op.f('ix_editorial_discussion_threads_id'), table_name='editorial_discussion_threads')
    op.drop_index(op.f('ix_editorial_discussion_threads_draft_id'), table_name='editorial_discussion_threads')
    op.drop_table('editorial_discussion_threads')
    op.drop_index(op.f('ix_publication_records_id'), table_name='publication_records')
    op.drop_index(op.f('ix_publication_records_article_id'), table_name='publication_records')
    op.drop_table('publication_records')
    # ### end Alembic commands ###
