"""sprint3_refinements

Revision ID: 11d38f12c21a
Revises: f4ab928c1872
Create Date: 2026-06-14 22:47:02.028861

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11d38f12c21a'
down_revision: str | Sequence[str] | None = 'f4ab928c1872'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('time_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_assigned', sa.Integer(), nullable=False),
    sa.Column('total_exposed', sa.Integer(), nullable=False),
    sa.Column('total_converted', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['experiment_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_metrics_id'), 'experiment_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_metrics_time_bucket'), 'experiment_metrics', ['time_bucket'], unique=False)
    op.add_column('experiment_assignments', sa.Column('assigned_by', sa.String(length=50), nullable=False, server_default='HASH'))
    op.add_column('experiment_assignments', sa.Column('assignment_reason', sa.String(length=255), nullable=True))
    op.add_column('experiment_assignments', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('experiments', sa.Column('primary_goal', sa.String(length=255), nullable=True))
    op.add_column('experiments', sa.Column('secondary_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'secondary_goals')
    op.drop_column('experiments', 'primary_goal')
    op.drop_column('experiment_assignments', 'is_locked')
    op.drop_column('experiment_assignments', 'assignment_reason')
    op.drop_column('experiment_assignments', 'assigned_by')
    op.drop_index(op.f('ix_experiment_metrics_time_bucket'), table_name='experiment_metrics')
    op.drop_index(op.f('ix_experiment_metrics_id'), table_name='experiment_metrics')
    op.drop_table('experiment_metrics')
    # ### end Alembic commands ###
