"""Add confidence to AI metadata

Revision ID: 1880defe2093
Revises: 4f2a693d7b24
Create Date: 2026-06-23 12:28:20.191518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1880defe2093'
down_revision: Union[str, Sequence[str], None] = '4f2a693d7b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_thumbnail_metadata', sa.Column('confidence', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_thumbnail_metadata', 'confidence')
    # ### end Alembic commands ###
