"""Phase 10 Sprint 6: Editorial Platform

Revision ID: 193631185173
Revises: 7e0ba724f996
Create Date: 2026-06-14 18:42:05.122429

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '193631185173'
down_revision: str | Sequence[str] | None = '7e0ba724f996'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_drafts_id'), 'editorial_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_editorial_drafts_status'), 'editorial_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_editorial_drafts_workspace_id'), 'editorial_drafts', ['workspace_id'], unique=False)
    op.create_table('editorial_draft_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_draft_versions_content_hash'), 'editorial_draft_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_editorial_draft_versions_draft_id'), 'editorial_draft_versions', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_draft_versions_id'), 'editorial_draft_versions', ['id'], unique=False)
    op.create_table('editorial_review_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('review_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_review_artifacts_draft_id'), 'editorial_review_artifacts', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_review_artifacts_id'), 'editorial_review_artifacts', ['id'], unique=False)
    op.drop_constraint('workspace_articles_article_id_fkey', 'workspace_articles', type_='foreignkey')
    op.alter_column('workspace_articles', 'article_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               postgresql_using='article_id::varchar',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('workspace_articles_article_id_fkey'), 'workspace_articles', 'processed_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workspace_articles', 'article_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_editorial_review_artifacts_id'), table_name='editorial_review_artifacts')
    op.drop_index(op.f('ix_editorial_review_artifacts_draft_id'), table_name='editorial_review_artifacts')
    op.drop_table('editorial_review_artifacts')
    op.drop_index(op.f('ix_editorial_draft_versions_id'), table_name='editorial_draft_versions')
    op.drop_index(op.f('ix_editorial_draft_versions_draft_id'), table_name='editorial_draft_versions')
    op.drop_index(op.f('ix_editorial_draft_versions_content_hash'), table_name='editorial_draft_versions')
    op.drop_table('editorial_draft_versions')
    op.drop_index(op.f('ix_editorial_drafts_workspace_id'), table_name='editorial_drafts')
    op.drop_index(op.f('ix_editorial_drafts_status'), table_name='editorial_drafts')
    op.drop_index(op.f('ix_editorial_drafts_id'), table_name='editorial_drafts')
    op.drop_table('editorial_drafts')
    # ### end Alembic commands ###
