"""Add RuntimeConfiguration

Revision ID: 21e118ea0303
Revises: 2e3fe06cfc16
Create Date: 2026-06-14 22:31:49.379972

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21e118ea0303'
down_revision: str | Sequence[str] | None = '2e3fe06cfc16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('environment_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_configurations_id'), 'runtime_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_runtime_configurations_key'), 'runtime_configurations', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_configurations_key'), table_name='runtime_configurations')
    op.drop_index(op.f('ix_runtime_configurations_id'), table_name='runtime_configurations')
    op.drop_table('runtime_configurations')
    # ### end Alembic commands ###
