"""Add TNT Knowledge Models

Revision ID: 24348ed3d71c
Revises: 2c250664080b
Create Date: 2026-06-14 17:37:48.871971

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24348ed3d71c'
down_revision: str | Sequence[str] | None = '2c250664080b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_episodes_conversation_id'), 'conversation_episodes', ['conversation_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active_research_session_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_name'), 'graph_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    op.create_table('graph_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_table('preference_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_memory_user_id'), 'preference_memory', ['user_id'], unique=False)
    op.create_table('procedural_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedural_memory_user_id'), 'procedural_memory', ['user_id'], unique=False)
    op.create_table('repair_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('execution_plan', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tnt_entity_nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tnt_entity_nodes_entity_type'), 'tnt_entity_nodes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_tnt_entity_nodes_id'), 'tnt_entity_nodes', ['id'], unique=False)
    op.create_table('tnt_topic_nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('taxonomy_category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_tnt_topic_nodes_name'), 'tnt_topic_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_tnt_topic_nodes_taxonomy_category'), 'tnt_topic_nodes', ['taxonomy_category'], unique=False)
    op.create_table('conflicting_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('claim', sa.String(length=500), nullable=False),
    sa.Column('existing_fact', sa.JSON(), nullable=True),
    sa.Column('new_fact', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('resolution_state', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.String(length=1000), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planner_version', sa.String(length=50), nullable=False),
    sa.Column('workflow_hash', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('optimizer_version', sa.String(length=50), nullable=False),
    sa.Column('provider_versions', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('resume_from', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_edge_type'), 'graph_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_table('graph_node_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_node_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_node_aliases_alias'), 'graph_node_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_graph_node_aliases_canonical_node_id'), 'graph_node_aliases', ['canonical_node_id'], unique=False)
    op.create_table('graph_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['graph_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['repair_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tnt_article_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['tnt_entity_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'entity_id', name='uq_tnt_article_entity')
    )
    op.create_index(op.f('ix_tnt_article_entities_article_id'), 'tnt_article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_tnt_article_entities_entity_id'), 'tnt_article_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tnt_article_entities_id'), 'tnt_article_entities', ['id'], unique=False)
    op.create_table('tnt_article_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_name'], ['tnt_topic_nodes.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'topic_name', name='uq_tnt_article_topic')
    )
    op.create_index(op.f('ix_tnt_article_topics_article_id'), 'tnt_article_topics', ['article_id'], unique=False)
    op.create_index(op.f('ix_tnt_article_topics_id'), 'tnt_article_topics', ['id'], unique=False)
    op.create_index(op.f('ix_tnt_article_topics_topic_name'), 'tnt_article_topics', ['topic_name'], unique=False)
    op.create_table('tnt_relationship_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['tnt_entity_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['tnt_entity_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'source_id', 'predicate', 'target_id', name='uq_tnt_relationship')
    )
    op.create_index(op.f('ix_tnt_relationship_edges_article_id'), 'tnt_relationship_edges', ['article_id'], unique=False)
    op.create_index(op.f('ix_tnt_relationship_edges_id'), 'tnt_relationship_edges', ['id'], unique=False)
    op.create_index(op.f('ix_tnt_relationship_edges_predicate'), 'tnt_relationship_edges', ['predicate'], unique=False)
    op.create_index(op.f('ix_tnt_relationship_edges_source_id'), 'tnt_relationship_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_tnt_relationship_edges_target_id'), 'tnt_relationship_edges', ['target_id'], unique=False)
    op.create_table('tnt_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('certainty', sa.String(length=50), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tnt_timeline_events_article_id'), 'tnt_timeline_events', ['article_id'], unique=False)
    op.create_index(op.f('ix_tnt_timeline_events_event_type'), 'tnt_timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tnt_timeline_events_id'), 'tnt_timeline_events', ['id'], unique=False)
    op.create_table('ai_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_artifacts_article_id'), 'ai_artifacts', ['article_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_artifact_type'), 'ai_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_id'), 'ai_artifacts', ['id'], unique=False)
    op.create_table('artifact_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('graph_node_id', sa.String(length=36), nullable=True),
    sa.Column('graph_edge_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['ai_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_edge_id'], ['graph_edges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_references_artifact_id'), 'artifact_references', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_references_graph_edge_id'), 'artifact_references', ['graph_edge_id'], unique=False)
    op.create_index(op.f('ix_artifact_references_graph_node_id'), 'artifact_references', ['graph_node_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('precision', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['ai_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_artifact_references_graph_node_id'), table_name='artifact_references')
    op.drop_index(op.f('ix_artifact_references_graph_edge_id'), table_name='artifact_references')
    op.drop_index(op.f('ix_artifact_references_artifact_id'), table_name='artifact_references')
    op.drop_table('artifact_references')
    op.drop_index(op.f('ix_ai_artifacts_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_artifact_type'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_article_id'), table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_index(op.f('ix_tnt_timeline_events_id'), table_name='tnt_timeline_events')
    op.drop_index(op.f('ix_tnt_timeline_events_event_type'), table_name='tnt_timeline_events')
    op.drop_index(op.f('ix_tnt_timeline_events_article_id'), table_name='tnt_timeline_events')
    op.drop_table('tnt_timeline_events')
    op.drop_index(op.f('ix_tnt_relationship_edges_target_id'), table_name='tnt_relationship_edges')
    op.drop_index(op.f('ix_tnt_relationship_edges_source_id'), table_name='tnt_relationship_edges')
    op.drop_index(op.f('ix_tnt_relationship_edges_predicate'), table_name='tnt_relationship_edges')
    op.drop_index(op.f('ix_tnt_relationship_edges_id'), table_name='tnt_relationship_edges')
    op.drop_index(op.f('ix_tnt_relationship_edges_article_id'), table_name='tnt_relationship_edges')
    op.drop_table('tnt_relationship_edges')
    op.drop_index(op.f('ix_tnt_article_topics_topic_name'), table_name='tnt_article_topics')
    op.drop_index(op.f('ix_tnt_article_topics_id'), table_name='tnt_article_topics')
    op.drop_index(op.f('ix_tnt_article_topics_article_id'), table_name='tnt_article_topics')
    op.drop_table('tnt_article_topics')
    op.drop_index(op.f('ix_tnt_article_entities_id'), table_name='tnt_article_entities')
    op.drop_index(op.f('ix_tnt_article_entities_entity_id'), table_name='tnt_article_entities')
    op.drop_index(op.f('ix_tnt_article_entities_article_id'), table_name='tnt_article_entities')
    op.drop_table('tnt_article_entities')
    op.drop_table('research_artifacts')
    op.drop_table('repair_tasks')
    op.drop_table('graph_snapshots')
    op.drop_index(op.f('ix_graph_node_aliases_canonical_node_id'), table_name='graph_node_aliases')
    op.drop_index(op.f('ix_graph_node_aliases_alias'), table_name='graph_node_aliases')
    op.drop_table('graph_node_aliases')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_edge_type'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('execution_attempts')
    op.drop_table('evidence_trees')
    op.drop_table('conflicting_observations')
    op.drop_index(op.f('ix_tnt_topic_nodes_taxonomy_category'), table_name='tnt_topic_nodes')
    op.drop_index(op.f('ix_tnt_topic_nodes_name'), table_name='tnt_topic_nodes')
    op.drop_table('tnt_topic_nodes')
    op.drop_index(op.f('ix_tnt_entity_nodes_id'), table_name='tnt_entity_nodes')
    op.drop_index(op.f('ix_tnt_entity_nodes_entity_type'), table_name='tnt_entity_nodes')
    op.drop_table('tnt_entity_nodes')
    op.drop_table('research_sessions')
    op.drop_table('repair_plans')
    op.drop_index(op.f('ix_procedural_memory_user_id'), table_name='procedural_memory')
    op.drop_table('procedural_memory')
    op.drop_index(op.f('ix_preference_memory_user_id'), table_name='preference_memory')
    op.drop_table('preference_memory')
    op.drop_table('graph_versions')
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_name'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_conversation_episodes_conversation_id'), table_name='conversation_episodes')
    op.drop_table('conversation_episodes')
    # ### end Alembic commands ###
