"""Add CategoryDeskProjection

Revision ID: 25de4c55dc3f
Revises: 09a793a1c42a
Create Date: 2026-08-07 21:35:31.984532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25de4c55dc3f'
down_revision: Union[str, Sequence[str], None] = '09a793a1c42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_desk_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_slug', sa.String(length=64), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('article_ids', sa.JSON(), nullable=False),
    sa.Column('projection_version', sa.String(length=32), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('build_duration_ms', sa.Integer(), nullable=False),
    sa.Column('rebuilt_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_desk_projections_category_slug'), 'category_desk_projections', ['category_slug'], unique=False)
    op.create_index(op.f('ix_category_desk_projections_created_at'), 'category_desk_projections', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_desk_projections_created_at'), table_name='category_desk_projections')
    op.drop_index(op.f('ix_category_desk_projections_category_slug'), table_name='category_desk_projections')
    op.drop_table('category_desk_projections')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
