"""Add Universal Projection Engine models

Revision ID: 267f4032596c
Revises: 5dce7d3bbb38
Create Date: 2026-06-14 21:07:09.993203

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '267f4032596c'
down_revision: str | Sequence[str] | None = '5dce7d3bbb38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projection_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projection_group', sa.String(length=100), nullable=False),
    sa.Column('projector_name', sa.String(length=100), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('max_latency_ms', sa.Float(), nullable=False),
    sa.Column('replay_duration_ms', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('last_processed_event_id', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projector_name')
    )
    op.create_index(op.f('ix_projection_telemetry_id'), 'projection_telemetry', ['id'], unique=False)
    op.add_column('ai_interaction_metrics', sa.Column('projection_version', sa.Integer(), nullable=False))
    op.add_column('article_metrics', sa.Column('projection_version', sa.Integer(), nullable=False))
    op.add_column('distribution_metrics', sa.Column('projection_version', sa.Integer(), nullable=False))
    op.add_column('engagement_metrics', sa.Column('projection_version', sa.Integer(), nullable=False))
    op.add_column('projection_checkpoints', sa.Column('projection_group', sa.String(length=100), nullable=False))
    op.add_column('projection_checkpoints', sa.Column('projector_version', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_proj_chkpt_proj_event'), table_name='projection_checkpoints')
    op.create_index('ix_proj_chkpt_group_proj_event', 'projection_checkpoints', ['projection_group', 'projector_name', 'event_id'], unique=True)
    op.drop_column('projection_checkpoints', 'projection_version')
    op.add_column('projection_failures', sa.Column('projection_group', sa.String(length=100), nullable=False))
    op.add_column('projection_failures', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('projection_failures', sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projection_failures', sa.Column('next_attempt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projection_failures', sa.Column('resolved', sa.Integer(), nullable=False))
    op.drop_column('projection_failures', 'retry_count')
    op.add_column('search_metrics', sa.Column('projection_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_metrics', 'projection_version')
    op.add_column('projection_failures', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('projection_failures', 'resolved')
    op.drop_column('projection_failures', 'next_attempt')
    op.drop_column('projection_failures', 'retry_after')
    op.drop_column('projection_failures', 'attempt_count')
    op.drop_column('projection_failures', 'projection_group')
    op.add_column('projection_checkpoints', sa.Column('projection_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_proj_chkpt_group_proj_event', table_name='projection_checkpoints')
    op.create_index(op.f('ix_proj_chkpt_proj_event'), 'projection_checkpoints', ['projector_name', 'event_id'], unique=True)
    op.drop_column('projection_checkpoints', 'projector_version')
    op.drop_column('projection_checkpoints', 'projection_group')
    op.drop_column('engagement_metrics', 'projection_version')
    op.drop_column('distribution_metrics', 'projection_version')
    op.drop_column('article_metrics', 'projection_version')
    op.drop_column('ai_interaction_metrics', 'projection_version')
    op.drop_index(op.f('ix_projection_telemetry_id'), table_name='projection_telemetry')
    op.drop_table('projection_telemetry')
    # ### end Alembic commands ###
