"""Add Recommendation Engine models

Revision ID: 3158ee426be8
Revises: 267f4032596c
Create Date: 2026-06-14 21:14:46.111454

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3158ee426be8'
down_revision: str | Sequence[str] | None = '267f4032596c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_feature_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('primary_topic', sa.String(length=255), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('editorial_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_article_feature_vectors_id'), 'article_feature_vectors', ['id'], unique=False)
    op.create_table('user_affinity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.Enum('TOPIC', 'ENTITY', 'AUTHOR', 'ARTICLE', 'CATEGORY', 'TAG', 'COMPANY', 'PERSON', name='affinitysubjecttype'), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_affinity_profiles_id'), 'user_affinity_profiles', ['id'], unique=False)
    op.create_index('ix_user_affinity_user_subject', 'user_affinity_profiles', ['user_id', 'subject_type', 'subject_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_affinity_user_subject', table_name='user_affinity_profiles')
    op.drop_index(op.f('ix_user_affinity_profiles_id'), table_name='user_affinity_profiles')
    op.drop_table('user_affinity_profiles')
    op.drop_index(op.f('ix_article_feature_vectors_id'), table_name='article_feature_vectors')
    op.drop_table('article_feature_vectors')
    # ### end Alembic commands ###
