"""refine_funnels

Revision ID: 342c1b0d3ee0
Revises: e495bfd02d14
Create Date: 2026-06-14 22:55:58.852034

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '342c1b0d3ee0'
down_revision: str | Sequence[str] | None = 'e495bfd02d14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_metrics', sa.Column('average_completion_time_seconds', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('funnel_metrics', sa.Column('median_completion_time_seconds', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('funnel_states', sa.Column('state_version', sa.String(length=50), nullable=False, server_default='v1'))
    op.add_column('funnel_states', sa.Column('is_expired', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funnel_states', 'is_expired')
    op.drop_column('funnel_states', 'state_version')
    op.drop_column('funnel_metrics', 'median_completion_time_seconds')
    op.drop_column('funnel_metrics', 'average_completion_time_seconds')
    # ### end Alembic commands ###
