"""distribution architecture refinements

Revision ID: 362fa9a8c187
Revises: c4d41ecf2d70
Create Date: 2026-06-14 20:19:39.367887

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '362fa9a8c187'
down_revision: str | Sequence[str] | None = 'c4d41ecf2d70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolved_audience_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.Column('segment_version', sa.String(length=50), nullable=True),
    sa.Column('compiler_version', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolved_audience_snapshots_audience_id'), 'resolved_audience_snapshots', ['audience_id'], unique=False)
    op.create_index(op.f('ix_resolved_audience_snapshots_id'), 'resolved_audience_snapshots', ['id'], unique=False)
    op.create_table('distribution_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('send_as_digest', sa.Boolean(), nullable=False),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_configurations_audience_id'), 'distribution_configurations', ['audience_id'], unique=False)
    op.create_index(op.f('ix_distribution_configurations_draft_id'), 'distribution_configurations', ['draft_id'], unique=True)
    op.create_index(op.f('ix_distribution_configurations_id'), 'distribution_configurations', ['id'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['distribution_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_id'), 'delivery_events', ['id'], unique=False)
    op.drop_index(op.f('ix_newsletter_configurations_audience_id'), table_name='newsletter_configurations')
    op.drop_index(op.f('ix_newsletter_configurations_draft_id'), table_name='newsletter_configurations')
    op.drop_index(op.f('ix_newsletter_configurations_id'), table_name='newsletter_configurations')
    op.drop_table('newsletter_configurations')
    op.add_column('distribution_manifests', sa.Column('subject_type', sa.String(length=50), nullable=False, server_default='ARTICLE'))
    op.add_column('distribution_manifests', sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('distribution_manifests', sa.Column('audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('distribution_manifests', sa.Column('distribution_version', sa.String(length=50), nullable=False, server_default='1.0'))
    op.add_column('distribution_manifests', sa.Column('payload_version', sa.String(length=50), nullable=False, server_default='1.0'))
    op.add_column('distribution_manifests', sa.Column('content_checksum', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_manifests', 'content_checksum')
    op.drop_column('distribution_manifests', 'payload_version')
    op.drop_column('distribution_manifests', 'distribution_version')
    op.drop_column('distribution_manifests', 'audience')
    op.drop_column('distribution_manifests', 'channels')
    op.drop_column('distribution_manifests', 'subject_type')
    op.create_table('newsletter_configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audience_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_template', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preheader', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reply_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tracking_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('utm_campaign', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('send_as_digest', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('personalization_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], name=op.f('newsletter_configurations_draft_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('newsletter_configurations_pkey'))
    )
    op.create_index(op.f('ix_newsletter_configurations_id'), 'newsletter_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_configurations_draft_id'), 'newsletter_configurations', ['draft_id'], unique=True)
    op.create_index(op.f('ix_newsletter_configurations_audience_id'), 'newsletter_configurations', ['audience_id'], unique=False)
    op.drop_index(op.f('ix_delivery_events_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_distribution_configurations_id'), table_name='distribution_configurations')
    op.drop_index(op.f('ix_distribution_configurations_draft_id'), table_name='distribution_configurations')
    op.drop_index(op.f('ix_distribution_configurations_audience_id'), table_name='distribution_configurations')
    op.drop_table('distribution_configurations')
    op.drop_index(op.f('ix_resolved_audience_snapshots_id'), table_name='resolved_audience_snapshots')
    op.drop_index(op.f('ix_resolved_audience_snapshots_audience_id'), table_name='resolved_audience_snapshots')
    op.drop_table('resolved_audience_snapshots')
    # ### end Alembic commands ###
