"""Phase 11 Sprint 1: Distribution Models

Revision ID: 39dac2465873
Revises: 193631185173
Create Date: 2026-06-14 18:55:08.919647

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39dac2465873'
down_revision: str | Sequence[str] | None = '193631185173'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_manifests_artifact_id'), 'publishing_manifests', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_publishing_manifests_channel'), 'publishing_manifests', ['channel'], unique=False)
    op.create_index(op.f('ix_publishing_manifests_id'), 'publishing_manifests', ['id'], unique=False)
    op.add_column('editorial_drafts', sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editorial_drafts', 'publish_at')
    op.drop_index(op.f('ix_publishing_manifests_id'), table_name='publishing_manifests')
    op.drop_index(op.f('ix_publishing_manifests_channel'), table_name='publishing_manifests')
    op.drop_index(op.f('ix_publishing_manifests_artifact_id'), table_name='publishing_manifests')
    op.drop_table('publishing_manifests')
    # ### end Alembic commands ###
