"""Add newsletter subscriber and projection models

Revision ID: 3ce33590aa42
Revises: 304d7ec808a7
Create Date: 2026-06-23 09:34:25.611647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ce33590aa42'
down_revision: Union[str, Sequence[str], None] = '304d7ec808a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_stats_projection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_subscribers', sa.Integer(), nullable=False),
    sa.Column('pending_subscribers', sa.Integer(), nullable=False),
    sa.Column('confirmed_subscribers', sa.Integer(), nullable=False),
    sa.Column('unsubscribed', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'UNSUBSCRIBED', name='subscriptionstatus'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(), nullable=False),
    sa.Column('confirmation_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_confirmation_token'), 'newsletter_subscribers', ['confirmation_token'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), 'newsletter_subscribers', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_confirmation_token'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_table('newsletter_stats_projection')
    # ### end Alembic commands ###
