"""add story telemetry snapshot

Revision ID: 4c38685103c2
Revises: 516c78676397
Create Date: 2026-06-23 14:00:40.849235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c38685103c2'
down_revision: Union[str, Sequence[str], None] = '516c78676397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_telemetry_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('story_status', sa.String(length=50), nullable=False),
    sa.Column('story_age_hours', sa.Float(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('unique_readers', sa.Integer(), nullable=False),
    sa.Column('avg_read_time_seconds', sa.Float(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.Column('newsletter_clicks', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_telemetry_snapshots_captured_at'), 'story_telemetry_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_story_telemetry_snapshots_id'), 'story_telemetry_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_story_telemetry_snapshots_story_id'), 'story_telemetry_snapshots', ['story_id'], unique=False)
    op.create_unique_constraint('uq_related_story_pair', 'related_stories', ['source_story_id', 'target_story_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_related_story_pair', 'related_stories', type_='unique')
    op.drop_index(op.f('ix_story_telemetry_snapshots_story_id'), table_name='story_telemetry_snapshots')
    op.drop_index(op.f('ix_story_telemetry_snapshots_id'), table_name='story_telemetry_snapshots')
    op.drop_index(op.f('ix_story_telemetry_snapshots_captured_at'), table_name='story_telemetry_snapshots')
    op.drop_table('story_telemetry_snapshots')
    # ### end Alembic commands ###
