"""add_search_index_node

Revision ID: 4d9f653780b9
Revises: 99e760ec3c85
Create Date: 2026-06-14 23:07:18.554730

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d9f653780b9'
down_revision: str | Sequence[str] | None = '99e760ec3c85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tsvector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_checksum', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_index_nodes_id'), 'search_index_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_search_index_nodes_node_type'), 'search_index_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_search_index_nodes_source_id'), 'search_index_nodes', ['source_id'], unique=False)
    op.create_index(op.f('ix_search_index_nodes_workspace_id'), 'search_index_nodes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_index_nodes_workspace_id'), table_name='search_index_nodes')
    op.drop_index(op.f('ix_search_index_nodes_source_id'), table_name='search_index_nodes')
    op.drop_index(op.f('ix_search_index_nodes_node_type'), table_name='search_index_nodes')
    op.drop_index(op.f('ix_search_index_nodes_id'), table_name='search_index_nodes')
    op.drop_table('search_index_nodes')
    # ### end Alembic commands ###
