"""Add notebook embeddings

Revision ID: 4e111cb2473d
Revises: a757b185d94c
Create Date: 2026-06-12 13:26:34.904943

"""

from collections.abc import Sequence

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e111cb2473d"
down_revision: str | Sequence[str] | None = "a757b185d94c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace_notes", sa.Column("embedding_status", sa.String(length=50), nullable=False))
    op.add_column("workspace_notes", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column("workspace_notes", sa.Column("embedding_hash", sa.String(length=64), nullable=True))
    op.add_column("workspace_notes", sa.Column("embedding_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_workspace_notes_embedding",
        "workspace_notes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_workspace_notes_embedding_status"), "workspace_notes", ["embedding_status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_notes_embedding_status"), table_name="workspace_notes")
    op.drop_index(
        "ix_workspace_notes_embedding",
        table_name="workspace_notes",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("workspace_notes", "embedding_updated_at")
    op.drop_column("workspace_notes", "embedding_hash")
    op.drop_column("workspace_notes", "embedding")
    op.drop_column("workspace_notes", "embedding_status")
    # ### end Alembic commands ###
