"""Add AI Thumbnail Recovery schema

Revision ID: 4f2a693d7b24
Revises: 94c18d1647f5
Create Date: 2026-06-23 12:12:36.537376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2a693d7b24'
down_revision: Union[str, Sequence[str], None] = '94c18d1647f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_thumbnail_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_thumbnail_metadata_article_id'), 'ai_thumbnail_metadata', ['article_id'], unique=False)
    op.create_index(op.f('ix_ai_thumbnail_metadata_id'), 'ai_thumbnail_metadata', ['id'], unique=False)
    op.execute("DROP TABLE IF EXISTS tnt_editorial_decision_logs CASCADE")
    op.add_column('articles', sa.Column('thumbnail_type', sa.String(length=50), server_default='REAL_IMAGE', nullable=False))
    op.add_column('processed_articles', sa.Column('thumbnail_type', sa.String(length=50), server_default='REAL_IMAGE', nullable=False))
    op.add_column('processed_articles', sa.Column('thumbnail_generation_reason', sa.String(length=100), nullable=True))
    op.add_column('processed_articles', sa.Column('thumbnail_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_articles', 'thumbnail_generated_at')
    op.drop_column('processed_articles', 'thumbnail_generation_reason')
    op.drop_column('processed_articles', 'thumbnail_type')
    op.drop_column('articles', 'thumbnail_type')
    op.create_table('tnt_editorial_decision_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('freshness_multiplier', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('effective_score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ranking_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('algorithm_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('selection_reason_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('selection_reason_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tnt_editorial_decision_logs_pkey'))
    )
    op.create_index(op.f('ix_tnt_editorial_decision_logs_snapshot_id'), 'tnt_editorial_decision_logs', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_tnt_editorial_decision_logs_id'), 'tnt_editorial_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tnt_editorial_decision_logs_article_id'), 'tnt_editorial_decision_logs', ['article_id'], unique=False)
    op.drop_index(op.f('ix_ai_thumbnail_metadata_id'), table_name='ai_thumbnail_metadata')
    op.drop_index(op.f('ix_ai_thumbnail_metadata_article_id'), table_name='ai_thumbnail_metadata')
    op.drop_table('ai_thumbnail_metadata')
    # ### end Alembic commands ###
