"""Add source_event_id to StoryTimelineEvent

Revision ID: 516c78676397
Revises: 5cf8d99cb43a
Create Date: 2026-06-23 13:38:55.549376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516c78676397'
down_revision: Union[str, Sequence[str], None] = '5cf8d99cb43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_timeline_events', sa.Column('source_event_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'story_timeline_events', ['source_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_timeline_events', type_='unique')
    op.drop_column('story_timeline_events', 'source_event_id')
    # ### end Alembic commands ###
