"""phase_11_sprint_2_editorial_refinements

Revision ID: 52332bb3a66b
Revises: 39dac2465873
Create Date: 2026-06-14 19:15:11.938622

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52332bb3a66b'
down_revision: str | Sequence[str] | None = '39dac2465873'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_decisions_draft_id'), 'editorial_decisions', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_decisions_id'), 'editorial_decisions', ['id'], unique=False)
    op.create_table('editorial_draft_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['editorial_draft_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_draft_comments_draft_id'), 'editorial_draft_comments', ['draft_id'], unique=False)
    op.create_index(op.f('ix_editorial_draft_comments_id'), 'editorial_draft_comments', ['id'], unique=False)
    op.create_index(op.f('ix_editorial_draft_comments_parent_id'), 'editorial_draft_comments', ['parent_id'], unique=False)
    op.create_table('editorial_patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['editorial_review_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_patches_id'), 'editorial_patches', ['id'], unique=False)
    op.create_index(op.f('ix_editorial_patches_review_id'), 'editorial_patches', ['review_id'], unique=False)
    op.add_column('editorial_draft_versions', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('subtitle', sa.String(length=255), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('rendered_html', sa.Text(), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('cover_image', sa.Text(), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('editor_notes', sa.Text(), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('publishing_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_draft_versions', sa.Column('ai_review_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('editorial_drafts', sa.Column('scheduled_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_drafts', sa.Column('approved_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_drafts', sa.Column('published_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_drafts', sa.Column('reviewed_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_drafts', sa.Column('fact_checked_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_drafts', sa.Column('last_modified_by', sa.String(length=255), nullable=True))
    op.add_column('editorial_review_artifacts', sa.Column('review_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('editorial_review_artifacts', 'review_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editorial_review_artifacts', sa.Column('review_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('editorial_review_artifacts', 'review_sections')
    op.drop_column('editorial_drafts', 'last_modified_by')
    op.drop_column('editorial_drafts', 'fact_checked_by')
    op.drop_column('editorial_drafts', 'reviewed_by')
    op.drop_column('editorial_drafts', 'published_by')
    op.drop_column('editorial_drafts', 'approved_by')
    op.drop_column('editorial_drafts', 'scheduled_by')
    op.drop_column('editorial_draft_versions', 'ai_review_ids')
    op.drop_column('editorial_draft_versions', 'publishing_settings')
    op.drop_column('editorial_draft_versions', 'seo')
    op.drop_column('editorial_draft_versions', 'metadata_snapshot')
    op.drop_column('editorial_draft_versions', 'tags')
    op.drop_column('editorial_draft_versions', 'category')
    op.drop_column('editorial_draft_versions', 'editor_notes')
    op.drop_column('editorial_draft_versions', 'cover_image')
    op.drop_column('editorial_draft_versions', 'rendered_html')
    op.drop_column('editorial_draft_versions', 'slug')
    op.drop_column('editorial_draft_versions', 'subtitle')
    op.drop_column('editorial_draft_versions', 'title')
    op.drop_index(op.f('ix_editorial_patches_review_id'), table_name='editorial_patches')
    op.drop_index(op.f('ix_editorial_patches_id'), table_name='editorial_patches')
    op.drop_table('editorial_patches')
    op.drop_index(op.f('ix_editorial_draft_comments_parent_id'), table_name='editorial_draft_comments')
    op.drop_index(op.f('ix_editorial_draft_comments_id'), table_name='editorial_draft_comments')
    op.drop_index(op.f('ix_editorial_draft_comments_draft_id'), table_name='editorial_draft_comments')
    op.drop_table('editorial_draft_comments')
    op.drop_index(op.f('ix_editorial_decisions_id'), table_name='editorial_decisions')
    op.drop_index(op.f('ix_editorial_decisions_draft_id'), table_name='editorial_decisions')
    op.drop_table('editorial_decisions')
    # ### end Alembic commands ###
