"""Add profile_version

Revision ID: 55618131210a
Revises: b3909946d736
Create Date: 2026-06-14 21:35:26.727291

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55618131210a'
down_revision: str | Sequence[str] | None = 'b3909946d736'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_profiles', sa.Column('profile_version', sa.String(length=50), server_default="1.0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_profiles', 'profile_version')
    # ### end Alembic commands ###
