"""Add RelatedStory read model

Revision ID: 5cf8d99cb43a
Revises: e5928b74e96f
Create Date: 2026-06-23 13:32:11.596146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf8d99cb43a'
down_revision: Union[str, Sequence[str], None] = 'e5928b74e96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_story_id', sa.String(), nullable=False),
    sa.Column('target_story_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_stories_source_story_id'), 'related_stories', ['source_story_id'], unique=False)
    op.create_index(op.f('ix_related_stories_target_story_id'), 'related_stories', ['target_story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_stories_target_story_id'), table_name='related_stories')
    op.drop_index(op.f('ix_related_stories_source_story_id'), table_name='related_stories')
    op.drop_table('related_stories')
    # ### end Alembic commands ###
