"""Add analytics models

Revision ID: 5dce7d3bbb38
Revises: 6a6a8273b6a9
Create Date: 2026-06-14 20:45:05.824884

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5dce7d3bbb38'
down_revision: str | Sequence[str] | None = '6a6a8273b6a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interaction_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('patches_proposed', sa.Integer(), nullable=False),
    sa.Column('patches_accepted', sa.Integer(), nullable=False),
    sa.Column('patches_rejected', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name')
    )
    op.create_index(op.f('ix_ai_interaction_metrics_id'), 'ai_interaction_metrics', ['id'], unique=False)
    op.create_table('analytics_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_analytics_sessions_id'), 'analytics_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_sessions_user_id'), 'analytics_sessions', ['user_id'], unique=False)
    op.create_table('article_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('unique_views', sa.Integer(), nullable=False),
    sa.Column('total_read_time_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_read_time_seconds', sa.Float(), nullable=False),
    sa.Column('completed_reads', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_article_metrics_id'), 'article_metrics', ['id'], unique=False)
    op.create_table('distribution_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifest_id', sa.String(length=255), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('bounced', sa.Integer(), nullable=False),
    sa.Column('opened', sa.Integer(), nullable=False),
    sa.Column('clicked', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_id')
    )
    op.create_index(op.f('ix_distribution_metrics_id'), 'distribution_metrics', ['id'], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.String(length=255), nullable=False),
    sa.Column('total_opens', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('unsubscribes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id')
    )
    op.create_index(op.f('ix_engagement_metrics_id'), 'engagement_metrics', ['id'], unique=False)
    op.create_table('search_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('zero_result_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_string')
    )
    op.create_index(op.f('ix_search_metrics_id'), 'search_metrics', ['id'], unique=False)
    op.create_table('projection_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projector_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('projection_version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proj_chkpt_proj_event', 'projection_checkpoints', ['projector_name', 'event_id'], unique=True)
    op.create_index(op.f('ix_projection_checkpoints_id'), 'projection_checkpoints', ['id'], unique=False)
    op.create_table('projection_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projector_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projection_failures_event_id'), 'projection_failures', ['event_id'], unique=False)
    op.create_index(op.f('ix_projection_failures_id'), 'projection_failures', ['id'], unique=False)
    op.create_index(op.f('ix_projection_failures_projector_name'), 'projection_failures', ['projector_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projection_failures_projector_name'), table_name='projection_failures')
    op.drop_index(op.f('ix_projection_failures_id'), table_name='projection_failures')
    op.drop_index(op.f('ix_projection_failures_event_id'), table_name='projection_failures')
    op.drop_table('projection_failures')
    op.drop_index(op.f('ix_projection_checkpoints_id'), table_name='projection_checkpoints')
    op.drop_index('ix_proj_chkpt_proj_event', table_name='projection_checkpoints')
    op.drop_table('projection_checkpoints')
    op.drop_index(op.f('ix_search_metrics_id'), table_name='search_metrics')
    op.drop_table('search_metrics')
    op.drop_index(op.f('ix_engagement_metrics_id'), table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index(op.f('ix_distribution_metrics_id'), table_name='distribution_metrics')
    op.drop_table('distribution_metrics')
    op.drop_index(op.f('ix_article_metrics_id'), table_name='article_metrics')
    op.drop_table('article_metrics')
    op.drop_index(op.f('ix_analytics_sessions_user_id'), table_name='analytics_sessions')
    op.drop_index(op.f('ix_analytics_sessions_id'), table_name='analytics_sessions')
    op.drop_table('analytics_sessions')
    op.drop_index(op.f('ix_ai_interaction_metrics_id'), table_name='ai_interaction_metrics')
    op.drop_table('ai_interaction_metrics')
    # ### end Alembic commands ###
