"""Phase_4E

Revision ID: 5e319a49596e
Revises: e42734bd8082
Create Date: 2026-06-11 11:29:48.580365

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e319a49596e"
down_revision: str | Sequence[str] | None = "e42734bd8082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('mock_backup')
    op.add_column("ai_job_history", sa.Column("prompt_hash", sa.String(length=64), nullable=True))
    # op.add_column('ai_job_history', sa.Column('provider_metadata', sa.JSON(), nullable=False))
    # op.add_column('ai_job_history', sa.Column('enrichment_input_fingerprint', sa.String(length=64), nullable=True))
    # op.create_index(op.f('ix_ai_job_history_enrichment_input_fingerprint'), 'ai_job_history', ['enrichment_input_fingerprint'], unique=False)
    op.add_column("raw_articles", sa.Column("dead_letter_reason", sa.Text(), nullable=True))
    op.add_column("raw_articles", sa.Column("dead_letter_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_articles", "dead_letter_at")
    op.drop_column("raw_articles", "dead_letter_reason")
    # op.drop_index(op.f('ix_ai_job_history_enrichment_input_fingerprint'), table_name='ai_job_history')
    # op.drop_column('ai_job_history', 'enrichment_input_fingerprint')
    # op.drop_column('ai_job_history', 'provider_metadata')
    op.drop_column("ai_job_history", "prompt_hash")
    # op.create_table('mock_backup',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False)
    # )
    # ### end Alembic commands ###
