"""Add Workspaces models

Revision ID: 64ae3ba72b32
Revises: 731ffb0117b5
Create Date: 2026-06-12 10:36:19.417142

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64ae3ba72b32"
down_revision: str | Sequence[str] | None = "731ffb0117b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_type", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_id"), "workspaces", ["id"], unique=False)
    op.create_index(op.f("ix_workspaces_owner_id"), "workspaces", ["owner_id"], unique=False)
    op.create_index(op.f("ix_workspaces_owner_type"), "workspaces", ["owner_type"], unique=False)
    op.create_table(
        "workspace_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "conversation_id", name="uq_workspace_conversation"),
    )
    op.create_index(
        op.f("ix_workspace_conversations_conversation_id"), "workspace_conversations", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_workspace_conversations_id"), "workspace_conversations", ["id"], unique=False)
    op.create_index(
        op.f("ix_workspace_conversations_workspace_id"), "workspace_conversations", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspace_notes_id"), "workspace_notes", ["id"], unique=False)
    op.create_index(op.f("ix_workspace_notes_workspace_id"), "workspace_notes", ["workspace_id"], unique=False)
    op.create_table(
        "workspace_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["processed_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "article_id", name="uq_workspace_article"),
    )
    op.create_index(op.f("ix_workspace_articles_article_id"), "workspace_articles", ["article_id"], unique=False)
    op.create_index(op.f("ix_workspace_articles_id"), "workspace_articles", ["id"], unique=False)
    op.create_index(op.f("ix_workspace_articles_workspace_id"), "workspace_articles", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_articles_workspace_id"), table_name="workspace_articles")
    op.drop_index(op.f("ix_workspace_articles_id"), table_name="workspace_articles")
    op.drop_index(op.f("ix_workspace_articles_article_id"), table_name="workspace_articles")
    op.drop_table("workspace_articles")
    op.drop_index(op.f("ix_workspace_notes_workspace_id"), table_name="workspace_notes")
    op.drop_index(op.f("ix_workspace_notes_id"), table_name="workspace_notes")
    op.drop_table("workspace_notes")
    op.drop_index(op.f("ix_workspace_conversations_workspace_id"), table_name="workspace_conversations")
    op.drop_index(op.f("ix_workspace_conversations_id"), table_name="workspace_conversations")
    op.drop_index(op.f("ix_workspace_conversations_conversation_id"), table_name="workspace_conversations")
    op.drop_table("workspace_conversations")
    op.drop_index(op.f("ix_workspaces_owner_type"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_owner_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_id"), table_name="workspaces")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
