"""Editorial workflow and delivery hardening

Revision ID: 67e18a9a9f83
Revises: d437878f8fc2
Create Date: 2026-06-23 13:56:27.079552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67e18a9a9f83'
down_revision: Union[str, Sequence[str], None] = 'd437878f8fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_briefing_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_html', sa.String(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_briefing_versions_briefing_id'), 'newsletter_briefing_versions', ['briefing_id'], unique=False)
    op.create_index(op.f('ix_newsletter_briefing_versions_id'), 'newsletter_briefing_versions', ['id'], unique=False)
    pass
    op.add_column('newsletter_briefings', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.drop_column('newsletter_briefings', 'content_text')
    op.drop_column('newsletter_briefings', 'title')
    op.drop_column('newsletter_briefings', 'content_html')
    op.create_unique_constraint('uq_email_delivery_campaign_subscriber', 'newsletter_email_deliveries', ['campaign_id', 'subscriber_id'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_constraint('uq_email_delivery_campaign_subscriber', 'newsletter_email_deliveries', type_='unique')
    op.add_column('newsletter_briefings', sa.Column('content_html', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('newsletter_briefings', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('newsletter_briefings', sa.Column('content_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('newsletter_briefings', 'current_version_id')
    pass
    op.drop_index(op.f('ix_newsletter_briefing_versions_id'), table_name='newsletter_briefing_versions')
    op.drop_index(op.f('ix_newsletter_briefing_versions_briefing_id'), table_name='newsletter_briefing_versions')
    op.drop_table('newsletter_briefing_versions')
    # ### end Alembic commands ###
