"""add_agent_telemetry

Revision ID: 699875afef73
Revises: f6d13ffc3202
Create Date: 2026-06-14 23:50:35.367045

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '699875afef73'
down_revision: str | Sequence[str] | None = 'f6d13ffc3202'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('planner', sa.String(length=100), nullable=False),
    sa.Column('plan_version', sa.String(length=50), nullable=True),
    sa.Column('execution_graph_version', sa.String(length=50), nullable=True),
    sa.Column('memory_provider', sa.String(length=100), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('generation_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('recovery_count', sa.Integer(), nullable=False),
    sa.Column('reflection_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_telemetry_execution_id'), 'agent_telemetry', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_telemetry_session_id'), 'agent_telemetry', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_telemetry_session_id'), table_name='agent_telemetry')
    op.drop_index(op.f('ix_agent_telemetry_execution_id'), table_name='agent_telemetry')
    op.drop_table('agent_telemetry')
    # ### end Alembic commands ###
