"""Add EventEnvelope

Revision ID: 6a6a8273b6a9
Revises: 362fa9a8c187
Create Date: 2026-06-14 20:29:43.060111

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a6a8273b6a9'
down_revision: str | Sequence[str] | None = '362fa9a8c187'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('DISTRIBUTION', 'EDITORIAL', 'KNOWLEDGE', 'ANALYTICS', 'AUTH', 'SYSTEM', name='eventcategory'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.Enum('ARTICLE', 'NEWSLETTER', 'DISTRIBUTION_JOB', 'PUBLICATION', 'COMMENT', 'ENTITY', 'TOPIC', 'USER', 'WORKSPACE', name='eventsubjecttype'), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('causation_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('event_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_envelopes_category'), 'event_envelopes', ['category'], unique=False)
    op.create_index(op.f('ix_event_envelopes_causation_id'), 'event_envelopes', ['causation_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_correlation_id'), 'event_envelopes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_event_type'), 'event_envelopes', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_envelopes_id'), 'event_envelopes', ['id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_provider'), 'event_envelopes', ['provider'], unique=False)
    op.create_index(op.f('ix_event_envelopes_provider_event_id'), 'event_envelopes', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_subject_id'), 'event_envelopes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_subject_type'), 'event_envelopes', ['subject_type'], unique=False)
    op.create_index(op.f('ix_event_envelopes_trace_id'), 'event_envelopes', ['trace_id'], unique=False)
    op.drop_index(op.f('ix_delivery_events_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['distribution_jobs.id'], name=op.f('delivery_events_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('delivery_events_pkey'))
    )
    op.create_index(op.f('ix_delivery_events_id'), 'delivery_events', ['id'], unique=False)
    op.drop_index(op.f('ix_event_envelopes_trace_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_subject_type'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_subject_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_provider_event_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_provider'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_event_type'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_correlation_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_causation_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_category'), table_name='event_envelopes')
    op.drop_table('event_envelopes')
    # ### end Alembic commands ###
