"""add_why_this_matters

Revision ID: 731ffb0117b5
Revises: 75fe71a04f91
Create Date: 2026-06-11 21:14:12.612831

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "731ffb0117b5"
down_revision: str | Sequence[str] | None = "75fe71a04f91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processed_articles", sa.Column("why_this_matters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processed_articles", "why_this_matters")
    # ### end Alembic commands ###
