"""Add behavioral models and privacy settings

Revision ID: 74a94c2b9b77
Revises: ce4cd928cdb1
Create Date: 2026-06-14 09:58:29.844694

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74a94c2b9b77"
down_revision: str | Sequence[str] | None = "ce4cd928cdb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_privacy_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("history_enabled", sa.Boolean(), nullable=False),
        sa.Column("analytics_enabled", sa.Boolean(), nullable=False),
        sa.Column("personalization_enabled", sa.Boolean(), nullable=False),
        sa.Column("behavioral_consent_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_privacy_settings_id"), "user_privacy_settings", ["id"], unique=False)
    op.create_table(
        "behavioral_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("anonymous_id", sa.String(length=36), nullable=True),
        sa.Column("article_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_version", sa.String(length=20), nullable=False),
        sa.Column("content_version", sa.String(length=50), nullable=True),
        sa.Column("scroll_percent", sa.Integer(), nullable=True),
        sa.Column("reading_time_seconds", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("referrer", sa.String(length=255), nullable=True),
        sa.Column("metadata_payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["processed_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_behav_events_anon_session", "behavioral_events", ["anonymous_id", "session_id"], unique=False)
    op.create_index("ix_behav_events_user_session", "behavioral_events", ["user_id", "session_id"], unique=False)
    op.create_index(op.f("ix_behavioral_events_anonymous_id"), "behavioral_events", ["anonymous_id"], unique=False)
    op.create_index(op.f("ix_behavioral_events_article_id"), "behavioral_events", ["article_id"], unique=False)
    op.create_index(op.f("ix_behavioral_events_event_id"), "behavioral_events", ["event_id"], unique=True)
    op.create_index(op.f("ix_behavioral_events_event_type"), "behavioral_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_behavioral_events_id"), "behavioral_events", ["id"], unique=False)
    op.create_index(op.f("ix_behavioral_events_occurred_at"), "behavioral_events", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_behavioral_events_session_id"), "behavioral_events", ["session_id"], unique=False)
    op.create_index(op.f("ix_behavioral_events_user_id"), "behavioral_events", ["user_id"], unique=False)
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("anonymous_id", sa.String(length=36), nullable=True),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_reading_seconds", sa.Integer(), nullable=False),
        sa.Column("completion_percentage", sa.Integer(), nullable=False),
        sa.Column("max_scroll_percent", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["processed_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reading_sessions_anonymous_id"), "reading_sessions", ["anonymous_id"], unique=False)
    op.create_index(op.f("ix_reading_sessions_article_id"), "reading_sessions", ["article_id"], unique=False)
    op.create_index(op.f("ix_reading_sessions_id"), "reading_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_reading_sessions_is_completed"), "reading_sessions", ["is_completed"], unique=False)
    op.create_index(
        op.f("ix_reading_sessions_last_activity_at"), "reading_sessions", ["last_activity_at"], unique=False
    )
    op.create_index(op.f("ix_reading_sessions_session_id"), "reading_sessions", ["session_id"], unique=True)
    op.create_index(op.f("ix_reading_sessions_user_id"), "reading_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_sessions_user_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_session_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_last_activity_at"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_is_completed"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_article_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_anonymous_id"), table_name="reading_sessions")
    op.drop_table("reading_sessions")
    op.drop_index(op.f("ix_behavioral_events_user_id"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_session_id"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_occurred_at"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_id"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_event_type"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_event_id"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_article_id"), table_name="behavioral_events")
    op.drop_index(op.f("ix_behavioral_events_anonymous_id"), table_name="behavioral_events")
    op.drop_index("ix_behav_events_user_session", table_name="behavioral_events")
    op.drop_index("ix_behav_events_anon_session", table_name="behavioral_events")
    op.drop_table("behavioral_events")
    op.drop_index(op.f("ix_user_privacy_settings_id"), table_name="user_privacy_settings")
    op.drop_table("user_privacy_settings")
    # ### end Alembic commands ###
