"""Add cluster_size to ProcessedArticle

Revision ID: 75fe71a04f91
Revises: b6b59202870b
Create Date: 2026-06-11 10:36:36.567767

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75fe71a04f91"
down_revision: str | Sequence[str] | None = "b6b59202870b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processed_articles", sa.Column("cluster_size", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processed_articles", "cluster_size")
    # ### end Alembic commands ###
