"""Add Story domain and separate lifecycle statuses

Revision ID: 79a3f7ebaacd
Revises: 1880defe2093
Create Date: 2026-06-23 13:01:50.193432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79a3f7ebaacd'
down_revision: Union[str, Sequence[str], None] = '1880defe2093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MONITORING', 'DORMANT', 'ARCHIVED', name='storystatus'), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('primary_article_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('story_id', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('editorial_status', sa.String(length=50), nullable=False, server_default='DRAFT'))
    op.add_column('articles', sa.Column('publication_status', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('scheduled_by', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_articles_editorial_status'), 'articles', ['editorial_status'], unique=False)
    op.create_index(op.f('ix_articles_publication_status'), 'articles', ['publication_status'], unique=False)
    op.create_index(op.f('ix_articles_story_id'), 'articles', ['story_id'], unique=False)
    op.add_column('processed_articles', sa.Column('story_id', sa.String(), nullable=True))
    op.add_column('processed_articles', sa.Column('editorial_status', sa.String(length=50), nullable=False, server_default='DRAFT'))
    op.add_column('processed_articles', sa.Column('publication_status', sa.String(length=50), nullable=True))
    op.add_column('processed_articles', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processed_articles', sa.Column('scheduled_by', sa.String(length=150), nullable=True))
    op.alter_column('processed_articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_processed_articles_editorial_status'), 'processed_articles', ['editorial_status'], unique=False)
    op.create_index(op.f('ix_processed_articles_publication_status'), 'processed_articles', ['publication_status'], unique=False)
    op.create_foreign_key(None, 'processed_articles', 'stories', ['story_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_articles', type_='foreignkey')
    op.drop_index(op.f('ix_processed_articles_publication_status'), table_name='processed_articles')
    op.drop_index(op.f('ix_processed_articles_editorial_status'), table_name='processed_articles')
    op.alter_column('processed_articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('processed_articles', 'scheduled_by')
    op.drop_column('processed_articles', 'scheduled_for')
    op.drop_column('processed_articles', 'publication_status')
    op.drop_column('processed_articles', 'editorial_status')
    op.drop_column('processed_articles', 'story_id')
    op.drop_index(op.f('ix_articles_story_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_publication_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_editorial_status'), table_name='articles')
    op.drop_column('articles', 'scheduled_by')
    op.drop_column('articles', 'scheduled_for')
    op.drop_column('articles', 'publication_status')
    op.drop_column('articles', 'editorial_status')
    op.drop_column('articles', 'story_id')
    op.drop_table('stories')
    # ### end Alembic commands ###
