"""Add StoryTimelineEvent

Revision ID: 79cca561ba7d
Revises: b8539edc090a
Create Date: 2026-06-23 13:28:43.022743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cca561ba7d'
down_revision: Union[str, Sequence[str], None] = 'b8539edc090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('milestone_type', sa.Enum('INITIAL_BREAK', 'MAJOR_UPDATE', 'OFFICIAL_RESPONSE', 'MARKET_REACTION', 'FOLLOW_UP', 'ANALYSIS', name='storymilestonetype'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_timeline_events_occurred_at'), 'story_timeline_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_story_timeline_events_story_id'), 'story_timeline_events', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_timeline_events_story_id'), table_name='story_timeline_events')
    op.drop_index(op.f('ix_story_timeline_events_occurred_at'), table_name='story_timeline_events')
    op.drop_table('story_timeline_events')
    # ### end Alembic commands ###
