"""add story dashboard projection

Revision ID: 7cda3b03251f
Revises: fa75a1f4d104
Create Date: 2026-06-23 14:24:03.630868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cda3b03251f'
down_revision: Union[str, Sequence[str], None] = 'fa75a1f4d104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_dashboard_projections',
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('editorial_status', sa.String(length=50), nullable=False),
    sa.Column('publication_status', sa.String(length=50), nullable=False),
    sa.Column('unique_readers', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.Column('newsletter_clicks', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projection_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_index(op.f('ix_story_dashboard_projections_story_id'), 'story_dashboard_projections', ['story_id'], unique=False)
    op.add_column('story_assignment_decisions', sa.Column('decision_reason', sa.String(), nullable=True))
    op.drop_index(op.f('ix_story_assignment_decisions_decided_at'), table_name='story_assignment_decisions')
    op.drop_column('story_assignment_decisions', 'model_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_assignment_decisions', sa.Column('model_version', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_story_assignment_decisions_decided_at'), 'story_assignment_decisions', ['decided_at'], unique=False)
    op.drop_column('story_assignment_decisions', 'decision_reason')
    op.drop_index(op.f('ix_story_dashboard_projections_story_id'), table_name='story_dashboard_projections')
    op.drop_table('story_dashboard_projections')
    # ### end Alembic commands ###
