"""Add Personalization models

Revision ID: 7e0ba724f996
Revises: b37bbb713986
Create Date: 2026-06-14 18:21:03.058472

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e0ba724f996'
down_revision: str | Sequence[str] | None = 'b37bbb713986'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['tnt_entity_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_id', name='uq_followed_entity')
    )
    op.create_index(op.f('ix_followed_entities_entity_id'), 'followed_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_followed_entities_id'), 'followed_entities', ['id'], unique=False)
    op.create_index(op.f('ix_followed_entities_user_id'), 'followed_entities', ['user_id'], unique=False)
    op.create_table('followed_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_name'], ['tnt_topic_nodes.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_name', name='uq_followed_topic')
    )
    op.create_index(op.f('ix_followed_topics_id'), 'followed_topics', ['id'], unique=False)
    op.create_index(op.f('ix_followed_topics_topic_name'), 'followed_topics', ['topic_name'], unique=False)
    op.create_index(op.f('ix_followed_topics_user_id'), 'followed_topics', ['user_id'], unique=False)
    op.create_table('user_reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('read_progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reading_time_seconds', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_reading_history')
    )
    op.create_index(op.f('ix_user_reading_history_article_id'), 'user_reading_history', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_reading_history_id'), 'user_reading_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_reading_history_user_id'), 'user_reading_history', ['user_id'], unique=False)
    op.execute('DELETE FROM saved_articles')
    op.execute('DELETE FROM saved_articles')
    op.drop_constraint('saved_articles_article_id_fkey', 'saved_articles', type_='foreignkey')
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_saved_articles_article_id'), 'saved_articles', ['article_id'], unique=False)
    op.create_unique_constraint('uq_saved_article', 'saved_articles', ['user_id', 'article_id'])
    op.create_foreign_key(None, 'saved_articles', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_articles', type_='foreignkey')
    op.create_foreign_key(op.f('saved_articles_article_id_fkey'), 'saved_articles', 'processed_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_saved_article', 'saved_articles', type_='unique')
    op.drop_index(op.f('ix_saved_articles_article_id'), table_name='saved_articles')
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_reading_history_user_id'), table_name='user_reading_history')
    op.drop_index(op.f('ix_user_reading_history_id'), table_name='user_reading_history')
    op.drop_index(op.f('ix_user_reading_history_article_id'), table_name='user_reading_history')
    op.drop_table('user_reading_history')
    op.drop_index(op.f('ix_followed_topics_user_id'), table_name='followed_topics')
    op.drop_index(op.f('ix_followed_topics_topic_name'), table_name='followed_topics')
    op.drop_index(op.f('ix_followed_topics_id'), table_name='followed_topics')
    op.drop_table('followed_topics')
    op.drop_index(op.f('ix_followed_entities_user_id'), table_name='followed_entities')
    op.drop_index(op.f('ix_followed_entities_id'), table_name='followed_entities')
    op.drop_index(op.f('ix_followed_entities_entity_id'), table_name='followed_entities')
    op.drop_table('followed_entities')
    # ### end Alembic commands ###
