"""add_generation_telemetry

Revision ID: 7e85566f1d41
Revises: 4d9f653780b9
Create Date: 2026-06-14 23:17:31.152020

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e85566f1d41'
down_revision: str | Sequence[str] | None = '4d9f653780b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_latency_ms', sa.Integer(), nullable=False),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=False),
    sa.Column('validation_latency_ms', sa.Integer(), nullable=False),
    sa.Column('stream_latency_ms', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('retrievers_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_valid_citations', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_telemetry_id'), 'generation_telemetry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_telemetry_id'), table_name='generation_telemetry')
    op.drop_table('generation_telemetry')
    # ### end Alembic commands ###
