"""Add filter_reason

Revision ID: 7ee8081fe89e
Revises: 12341cb60600
Create Date: 2026-08-10 12:03:01.851234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ee8081fe89e'
down_revision: Union[str, Sequence[str], None] = '12341cb60600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certification_runs_run_id'), table_name='certification_runs')
    op.drop_table('certification_runs')
    op.drop_index(op.f('ix_daily_briefing_events_delivery'), table_name='daily_briefing_delivery_events')
    op.drop_table('daily_briefing_delivery_events')
    op.drop_index(op.f('ix_homepage_projections_created_at'), table_name='homepage_projections')
    op.drop_index(op.f('ix_homepage_projections_projection_version'), table_name='homepage_projections')
    op.drop_table('homepage_projections')
    op.drop_index(op.f('ix_category_desk_projections_category_slug'), table_name='category_desk_projections')
    op.drop_index(op.f('ix_category_desk_projections_created_at'), table_name='category_desk_projections')
    op.drop_table('category_desk_projections')
    op.drop_index(op.f('ix_certification_scenario_evidences_run_id'), table_name='certification_scenario_evidences')
    op.drop_index(op.f('ix_certification_scenario_evidences_scenario_id'), table_name='certification_scenario_evidences')
    op.drop_table('certification_scenario_evidences')
    op.alter_column('articles', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index('ix_article_read_model_embedding', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_daily_briefing_deliveries_edition'), table_name='daily_briefing_deliveries')
    op.drop_index(op.f('ix_daily_briefing_deliveries_subscriber'), table_name='daily_briefing_deliveries')
    op.drop_index(op.f('ix_daily_briefing_editions_date'), table_name='daily_briefing_editions')
    op.drop_index(op.f('ix_daily_briefing_items_article'), table_name='daily_briefing_items')
    op.drop_index(op.f('ix_daily_briefing_items_edition'), table_name='daily_briefing_items')
    op.alter_column('processed_articles', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index('ix_processed_articles_embedding', 'processed_articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('search_index_nodes', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_index(op.f('ix_webhook_events_provider_event'), table_name='webhook_events')
    op.alter_column('workspace_notes', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index('ix_workspace_notes_embedding', 'workspace_notes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_notes_embedding', table_name='workspace_notes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('workspace_notes', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_webhook_events_provider_event'), 'webhook_events', ['provider', 'event_id'], unique=False)
    op.alter_column('search_index_nodes', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_processed_articles_embedding', table_name='processed_articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('processed_articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_daily_briefing_items_edition'), 'daily_briefing_items', ['edition_id'], unique=False)
    op.create_index(op.f('ix_daily_briefing_items_article'), 'daily_briefing_items', ['article_id'], unique=False)
    op.create_index(op.f('ix_daily_briefing_editions_date'), 'daily_briefing_editions', ['edition_date'], unique=False)
    op.create_index(op.f('ix_daily_briefing_deliveries_subscriber'), 'daily_briefing_deliveries', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_daily_briefing_deliveries_edition'), 'daily_briefing_deliveries', ['edition_id'], unique=False)
    op.drop_index('ix_article_read_model_embedding', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('certification_scenario_evidences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scenario_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detection_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recovery_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('root_cause_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('explanation_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('event_loss', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('projection_consistent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('chain_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sla_passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['certification_runs.id'], name=op.f('certification_scenario_evidences_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certification_scenario_evidences_pkey'))
    )
    op.create_index(op.f('ix_certification_scenario_evidences_scenario_id'), 'certification_scenario_evidences', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_certification_scenario_evidences_run_id'), 'certification_scenario_evidences', ['run_id'], unique=False)
    op.create_table('category_desk_projections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('category_slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('article_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('projection_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('algorithm_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('policy_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('build_duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebuilt_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_desk_projections_pkey'))
    )
    op.create_index(op.f('ix_category_desk_projections_created_at'), 'category_desk_projections', ['created_at'], unique=False)
    op.create_index(op.f('ix_category_desk_projections_category_slug'), 'category_desk_projections', ['category_slug'], unique=False)
    op.create_table('homepage_projections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('projection_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ranking_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('pipeline_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('stories_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('explanation_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homepage_projections'))
    )
    op.create_index(op.f('ix_homepage_projections_projection_version'), 'homepage_projections', ['projection_version'], unique=False)
    op.create_index(op.f('ix_homepage_projections_created_at'), 'homepage_projections', ['created_at'], unique=False)
    op.create_table('daily_briefing_delivery_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['daily_briefing_deliveries.id'], name=op.f('daily_briefing_delivery_events_delivery_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_briefing_delivery_events_pkey'))
    )
    op.create_index(op.f('ix_daily_briefing_events_delivery'), 'daily_briefing_delivery_events', ['delivery_id'], unique=False)
    op.create_table('certification_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('certification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('certification_runner_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('baseline_run_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_scenarios', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('certification_runs_pkey'))
    )
    op.create_index(op.f('ix_certification_runs_run_id'), 'certification_runs', ['run_id'], unique=True)
    # ### end Alembic commands ###
