"""Add StoryHealthProjection and CoverageGapAnalytic

Revision ID: 9279ed9ae183
Revises: 7cda3b03251f
Create Date: 2026-06-23 14:40:29.671252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9279ed9ae183'
down_revision: Union[str, Sequence[str], None] = '7cda3b03251f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_gap_analytics',
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('search_volume_score', sa.Float(), nullable=True),
    sa.Column('coverage_strength', sa.Float(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('story_health_projections',
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('story_status', sa.String(length=50), nullable=True),
    sa.Column('days_since_activity', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('reawakening_signal_score', sa.Float(), nullable=True),
    sa.Column('projection_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_health_projections')
    op.drop_table('coverage_gap_analytics')
    # ### end Alembic commands ###
