"""add_missing_fields

Revision ID: 94c18d1647f5
Revises: 8561a227444b
Create Date: 2026-06-23 11:32:33.480490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94c18d1647f5'
down_revision: Union[str, Sequence[str], None] = '8561a227444b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_agent_name'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_projection_failures_event_id'), table_name='projection_failures')
    op.drop_index(op.f('ix_projection_failures_id'), table_name='projection_failures')
    op.drop_index(op.f('ix_projection_failures_projector_name'), table_name='projection_failures')
    op.drop_table('projection_failures')
    op.drop_index(op.f('ix_proj_chkpt_group_proj_event'), table_name='projection_checkpoints')
    op.drop_index(op.f('ix_projection_checkpoints_id'), table_name='projection_checkpoints')
    op.drop_table('projection_checkpoints')
    op.drop_index(op.f('ix_topic_aliases_alias'), table_name='topic_aliases')
    op.drop_index(op.f('ix_topic_aliases_id'), table_name='topic_aliases')
    op.drop_table('topic_aliases')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_tnt_editorial_decision_logs_article_id'), table_name='tnt_editorial_decision_logs')
    op.drop_index(op.f('ix_tnt_editorial_decision_logs_id'), table_name='tnt_editorial_decision_logs')
    op.drop_index(op.f('ix_tnt_editorial_decision_logs_snapshot_id'), table_name='tnt_editorial_decision_logs')
    op.drop_table('tnt_editorial_decision_logs')
    op.drop_index(op.f('ix_thumbnail_decision_log_article_id'), table_name='thumbnail_decision_log')
    op.drop_index(op.f('ix_thumbnail_decision_log_id'), table_name='thumbnail_decision_log')
    op.drop_table('thumbnail_decision_log')
    op.drop_index(op.f('ix_projection_telemetry_id'), table_name='projection_telemetry')
    op.drop_table('projection_telemetry')
    op.drop_index(op.f('ix_trending_topics_id'), table_name='trending_topics')
    op.drop_table('trending_topics')
    op.add_column('articles', sa.Column('freshness_score', sa.Numeric(), nullable=False))
    op.add_column('articles', sa.Column('engagement_score', sa.Numeric(), nullable=False))
    op.add_column('articles', sa.Column('final_score', sa.Numeric(), nullable=False))
    op.add_column('articles', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('published_status', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_articles_is_test_data'), table_name='articles')
    op.alter_column('processed_articles', 'thumbnail_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_processed_articles_is_test_data'), table_name='processed_articles')
    op.drop_column('processed_articles', 'thumbnail_width')
    op.drop_column('processed_articles', 'why_this_matters')
    op.drop_column('processed_articles', 'thumbnail_last_verified_at')
    op.drop_column('processed_articles', 'thumbnail_height')
    op.drop_column('processed_articles', 'thumbnail_content_type')
    op.drop_index(op.f('ix_raw_articles_is_test_data'), table_name='raw_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_articles_is_test_data'), 'raw_articles', ['is_test_data'], unique=False)
    op.add_column('processed_articles', sa.Column('thumbnail_content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processed_articles', sa.Column('thumbnail_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processed_articles', sa.Column('thumbnail_last_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('processed_articles', sa.Column('why_this_matters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('processed_articles', sa.Column('thumbnail_width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_processed_articles_is_test_data'), 'processed_articles', ['is_test_data'], unique=False)
    op.alter_column('processed_articles', 'thumbnail_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_articles_is_test_data'), 'articles', ['is_test_data'], unique=False)
    op.drop_column('articles', 'published_status')
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'final_score')
    op.drop_column('articles', 'engagement_score')
    op.drop_column('articles', 'freshness_score')
    op.create_table('trending_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trending_topics_pkey')),
    sa.UniqueConstraint('topic', name=op.f('trending_topics_topic_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_trending_topics_id'), 'trending_topics', ['id'], unique=False)
    op.create_table('projection_telemetry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projection_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('projector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('events_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('replay_duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('failure_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_processed_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_success', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('projection_telemetry_pkey')),
    sa.UniqueConstraint('projector_name', name=op.f('projection_telemetry_projector_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_projection_telemetry_id'), 'projection_telemetry', ['id'], unique=False)
    op.create_table('thumbnail_decision_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aspect_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('candidate_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('algorithm_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], name=op.f('thumbnail_decision_log_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('thumbnail_decision_log_pkey'))
    )
    op.create_index(op.f('ix_thumbnail_decision_log_id'), 'thumbnail_decision_log', ['id'], unique=False)
    op.create_index(op.f('ix_thumbnail_decision_log_article_id'), 'thumbnail_decision_log', ['article_id'], unique=False)
    op.create_table('tnt_editorial_decision_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('freshness_multiplier', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('effective_score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ranking_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('algorithm_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('selection_reason_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('selection_reason_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tnt_editorial_decision_logs_pkey'))
    )
    op.create_index(op.f('ix_tnt_editorial_decision_logs_snapshot_id'), 'tnt_editorial_decision_logs', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_tnt_editorial_decision_logs_id'), 'tnt_editorial_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tnt_editorial_decision_logs_article_id'), 'tnt_editorial_decision_logs', ['article_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey')),
    sa.UniqueConstraint('name', name=op.f('topics_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('topic_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('topic_aliases_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_aliases_pkey'))
    )
    op.create_index(op.f('ix_topic_aliases_id'), 'topic_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_topic_aliases_alias'), 'topic_aliases', ['alias'], unique=True)
    op.create_table('projection_checkpoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('projection_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('projector_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_envelopes.id'], name=op.f('projection_checkpoints_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projection_checkpoints_pkey'))
    )
    op.create_index(op.f('ix_projection_checkpoints_id'), 'projection_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_proj_chkpt_group_proj_event'), 'projection_checkpoints', ['projection_group', 'projector_name', 'event_id'], unique=True)
    op.create_table('projection_failures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stacktrace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('projection_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('retry_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_attempt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_envelopes.id'], name=op.f('projection_failures_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projection_failures_pkey'))
    )
    op.create_index(op.f('ix_projection_failures_projector_name'), 'projection_failures', ['projector_name'], unique=False)
    op.create_index(op.f('ix_projection_failures_id'), 'projection_failures', ['id'], unique=False)
    op.create_index(op.f('ix_projection_failures_event_id'), 'projection_failures', ['event_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_logs_pkey'))
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_logs_agent_name'), 'agent_logs', ['agent_name'], unique=False)
    # ### end Alembic commands ###
