"""add_cohorts

Revision ID: 99e760ec3c85
Revises: 342c1b0d3ee0
Create Date: 2026-06-14 22:59:28.793747

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99e760ec3c85'
down_revision: str | Sequence[str] | None = '342c1b0d3ee0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('refresh_mode', sa.String(length=50), nullable=False),
    sa.Column('parent_cohort_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_cohorts_key'), 'cohorts', ['key'], unique=True)
    op.create_table('cohort_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('cohort_version', sa.String(length=50), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('projection_version', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_memberships_cohort_id'), 'cohort_memberships', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_memberships_id'), 'cohort_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_memberships_subject_id'), 'cohort_memberships', ['subject_id'], unique=False)
    op.create_table('cohort_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('rule_capability', sa.String(length=100), nullable=False),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_rules_id'), 'cohort_rules', ['id'], unique=False)
    op.create_table('cohort_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('entered', sa.Integer(), nullable=False),
    sa.Column('exited', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_snapshots_cohort_id'), 'cohort_snapshots', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_snapshots_id'), 'cohort_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_snapshots_id'), table_name='cohort_snapshots')
    op.drop_index(op.f('ix_cohort_snapshots_cohort_id'), table_name='cohort_snapshots')
    op.drop_table('cohort_snapshots')
    op.drop_index(op.f('ix_cohort_rules_id'), table_name='cohort_rules')
    op.drop_table('cohort_rules')
    op.drop_index(op.f('ix_cohort_memberships_subject_id'), table_name='cohort_memberships')
    op.drop_index(op.f('ix_cohort_memberships_id'), table_name='cohort_memberships')
    op.drop_index(op.f('ix_cohort_memberships_cohort_id'), table_name='cohort_memberships')
    op.drop_table('cohort_memberships')
    op.drop_index(op.f('ix_cohorts_key'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
