"""add_thumbnail_retry_count

Revision ID: 9fc08ce30485
Revises: 9279ed9ae183
Create Date: 2026-08-01 07:00:18.779877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc08ce30485'
down_revision: Union[str, Sequence[str], None] = '9279ed9ae183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('thumbnail_status', sa.String(length=50), server_default='pending', nullable=False))
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.add_column('processed_articles', sa.Column('thumbnail_retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('processed_articles', sa.Column('thumbnail_last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_articles', 'thumbnail_last_attempt_at')
    op.drop_column('processed_articles', 'thumbnail_retry_count')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_column('articles', 'thumbnail_status')
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###
