"""add_sentiment_column

Revision ID: a1b2c3d4e5f6
Revises: 3f7c2b1a9d4e
Create Date: 2026-06-10 16:55:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "7b6d5e4c3a21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processed_articles", sa.Column("sentiment", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processed_articles", "sentiment")
    # ### end Alembic commands ###
