"""Add notebook fields and versions

Revision ID: a757b185d94c
Revises: c7d8a95797ac
Create Date: 2026-06-12 11:04:05.352784

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a757b185d94c"
down_revision: str | Sequence[str] | None = "c7d8a95797ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_note_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["workspace_notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspace_note_versions_id"), "workspace_note_versions", ["id"], unique=False)
    op.create_index(op.f("ix_workspace_note_versions_note_id"), "workspace_note_versions", ["note_id"], unique=False)
    op.add_column("workspace_notes", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("workspace_notes", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("workspace_notes", sa.Column("version_number", sa.Integer(), nullable=False))
    op.add_column("workspace_notes", sa.Column("last_ai_modified_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_notes", "last_ai_modified_at")
    op.drop_column("workspace_notes", "version_number")
    op.drop_column("workspace_notes", "summary")
    op.drop_column("workspace_notes", "title")
    op.drop_index(op.f("ix_workspace_note_versions_note_id"), table_name="workspace_note_versions")
    op.drop_index(op.f("ix_workspace_note_versions_id"), table_name="workspace_note_versions")
    op.drop_table("workspace_note_versions")
    # ### end Alembic commands ###
