"""Add embedding to ArticleReadModel

Revision ID: b37bbb713986
Revises: 24348ed3d71c
Create Date: 2026-06-14 18:06:20.566977

"""
from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b37bbb713986'
down_revision: str | Sequence[str] | None = '24348ed3d71c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('importance_score', sa.Numeric(), server_default='0.0', nullable=False))
    op.add_column('articles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('articles', sa.Column('embedding_version', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.create_index('ix_article_read_model_embedding', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_read_model_embedding', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('articles', 'embedding_model')
    op.drop_column('articles', 'embedding_version')
    op.drop_column('articles', 'embedding')
    op.drop_column('articles', 'importance_score')
    # ### end Alembic commands ###
