"""Add RecommendationProfile

Revision ID: b3909946d736
Revises: 3158ee426be8
Create Date: 2026-06-14 21:25:22.632834

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3909946d736'
down_revision: str | Sequence[str] | None = '3158ee426be8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('feature_vector_id', sa.String(length=255), nullable=True),
    sa.Column('ranking_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_recommendation_profiles_id'), 'recommendation_profiles', ['id'], unique=False)
    op.add_column('article_feature_vectors', sa.Column('behavior_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('article_feature_vectors', sa.Column('social_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('article_feature_vectors', sa.Column('distribution_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('article_feature_vectors', sa.Column('engagement_score', sa.Float(), server_default='0.0', nullable=False))
    op.drop_column('article_feature_vectors', 'quality_score')
    op.drop_column('article_feature_vectors', 'popularity_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_feature_vectors', sa.Column('popularity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('article_feature_vectors', sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('article_feature_vectors', 'engagement_score')
    op.drop_column('article_feature_vectors', 'distribution_score')
    op.drop_column('article_feature_vectors', 'social_score')
    op.drop_column('article_feature_vectors', 'behavior_score')
    op.drop_index(op.f('ix_recommendation_profiles_id'), table_name='recommendation_profiles')
    op.drop_table('recommendation_profiles')
    # ### end Alembic commands ###
