"""Add cluster fields

Revision ID: b6b59202870b
Revises: ee9b2cc63fb4
Create Date: 2026-06-11 10:09:10.189852

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6b59202870b"
down_revision: str | Sequence[str] | None = "ee9b2cc63fb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processed_articles", sa.Column("cluster_id", sa.String(length=36), nullable=True))
    op.add_column("processed_articles", sa.Column("cluster_score", sa.Numeric(), nullable=True))
    op.add_column("processed_articles", sa.Column("cluster_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_processed_articles_cluster_id"), "processed_articles", ["cluster_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_articles_cluster_id"), table_name="processed_articles")
    op.drop_column("processed_articles", "cluster_updated_at")
    op.drop_column("processed_articles", "cluster_score")
    op.drop_column("processed_articles", "cluster_id")
    # ### end Alembic commands ###
