"""Drop impact_score from articles

Revision ID: b8539edc090a
Revises: 79a3f7ebaacd
Create Date: 2026-06-23 13:18:12.585411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8539edc090a'
down_revision: Union[str, Sequence[str], None] = '79a3f7ebaacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'impact_score')
    op.drop_column('processed_articles', 'impact_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_articles', sa.Column('impact_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('impact_score', sa.NUMERIC(), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
