"""phase_12_sprint_1_distribution_models

Revision ID: bd0dfd57b9f8
Revises: 0cc9d36826bf
Create Date: 2026-06-14 19:42:09.739791

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd0dfd57b9f8'
down_revision: str | Sequence[str] | None = '0cc9d36826bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_record_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_record_id'], ['publication_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_manifests_id'), 'distribution_manifests', ['id'], unique=False)
    op.create_table('distribution_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'VALIDATING', 'PREFLIGHT', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED', name='distributionjobstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['distribution_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_jobs_channel'), 'distribution_jobs', ['channel'], unique=False)
    op.create_index(op.f('ix_distribution_jobs_id'), 'distribution_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_distribution_jobs_subject_id'), 'distribution_jobs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_distribution_jobs_subject_type'), 'distribution_jobs', ['subject_type'], unique=False)
    op.create_table('delivery_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'VALIDATING', 'PREFLIGHT', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED', name='distributionjobstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['distribution_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_reports_id'), 'delivery_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_publishing_manifests_artifact_id'), table_name='publishing_manifests')
    op.drop_index(op.f('ix_publishing_manifests_channel'), table_name='publishing_manifests')
    op.drop_index(op.f('ix_publishing_manifests_id'), table_name='publishing_manifests')
    op.drop_table('publishing_manifests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_manifests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('publishing_manifests_pkey'))
    )
    op.create_index(op.f('ix_publishing_manifests_id'), 'publishing_manifests', ['id'], unique=False)
    op.create_index(op.f('ix_publishing_manifests_channel'), 'publishing_manifests', ['channel'], unique=False)
    op.create_index(op.f('ix_publishing_manifests_artifact_id'), 'publishing_manifests', ['artifact_id'], unique=False)
    op.drop_index(op.f('ix_delivery_reports_id'), table_name='delivery_reports')
    op.drop_table('delivery_reports')
    op.drop_index(op.f('ix_distribution_jobs_subject_type'), table_name='distribution_jobs')
    op.drop_index(op.f('ix_distribution_jobs_subject_id'), table_name='distribution_jobs')
    op.drop_index(op.f('ix_distribution_jobs_id'), table_name='distribution_jobs')
    op.drop_index(op.f('ix_distribution_jobs_channel'), table_name='distribution_jobs')
    op.drop_table('distribution_jobs')
    op.drop_index(op.f('ix_distribution_manifests_id'), table_name='distribution_manifests')
    op.drop_table('distribution_manifests')
    # ### end Alembic commands ###
