"""phase12_sprint3_newsletters

Revision ID: c4d41ecf2d70
Revises: fce3cf70a42c
Create Date: 2026-06-14 20:03:45.568224

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4d41ecf2d70'
down_revision: str | Sequence[str] | None = 'fce3cf70a42c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('send_as_digest', sa.Boolean(), nullable=False),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['editorial_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_configurations_audience_id'), 'newsletter_configurations', ['audience_id'], unique=False)
    op.create_index(op.f('ix_newsletter_configurations_draft_id'), 'newsletter_configurations', ['draft_id'], unique=True)
    op.create_index(op.f('ix_newsletter_configurations_id'), 'newsletter_configurations', ['id'], unique=False)
    op.add_column('delivery_preferences', sa.Column('priority', sa.Integer(), server_default='100', nullable=False))
    op.add_column('delivery_preferences', sa.Column('batch_window', sa.String(length=50), nullable=True))
    op.add_column('delivery_preferences', sa.Column('digest_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('editorial_drafts', sa.Column('artifact_type', sa.String(length=50), server_default='ARTICLE', nullable=False))
    op.add_column('segments', sa.Column('compiled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('segments', sa.Column('compiler_version', sa.String(length=50), nullable=True))
    op.add_column('subscriber_contacts', sa.Column('verification_status', sa.String(length=50), server_default='UNVERIFIED', nullable=False))
    op.add_column('subscriber_contacts', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriber_contacts', sa.Column('verification_method', sa.String(length=100), nullable=True))
    op.drop_column('subscriber_contacts', 'verified')
    op.add_column('subscription_events', sa.Column('actor', sa.String(length=50), server_default='SYSTEM', nullable=False))
    op.add_column('subscription_events', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_events', 'reason')
    op.drop_column('subscription_events', 'actor')
    op.add_column('subscriber_contacts', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('subscriber_contacts', 'verification_method')
    op.drop_column('subscriber_contacts', 'verified_at')
    op.drop_column('subscriber_contacts', 'verification_status')
    op.drop_column('segments', 'compiler_version')
    op.drop_column('segments', 'compiled_at')
    op.drop_column('editorial_drafts', 'artifact_type')
    op.drop_column('delivery_preferences', 'digest_enabled')
    op.drop_column('delivery_preferences', 'batch_window')
    op.drop_column('delivery_preferences', 'priority')
    op.drop_index(op.f('ix_newsletter_configurations_id'), table_name='newsletter_configurations')
    op.drop_index(op.f('ix_newsletter_configurations_draft_id'), table_name='newsletter_configurations')
    op.drop_index(op.f('ix_newsletter_configurations_audience_id'), table_name='newsletter_configurations')
    op.drop_table('newsletter_configurations')
    # ### end Alembic commands ###
