"""Add WorkspaceActivity

Revision ID: c7d8a95797ac
Revises: 64ae3ba72b32
Create Date: 2026-06-12 10:52:35.233790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7d8a95797ac"
down_revision: str | Sequence[str] | None = "64ae3ba72b32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspace_activities_created_at"), "workspace_activities", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspace_activities_event_type"), "workspace_activities", ["event_type"], unique=False)
    op.create_index(op.f("ix_workspace_activities_id"), "workspace_activities", ["id"], unique=False)
    op.create_index(
        op.f("ix_workspace_activities_workspace_id"), "workspace_activities", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_activities_workspace_id"), table_name="workspace_activities")
    op.drop_index(op.f("ix_workspace_activities_id"), table_name="workspace_activities")
    op.drop_index(op.f("ix_workspace_activities_event_type"), table_name="workspace_activities")
    op.drop_index(op.f("ix_workspace_activities_created_at"), table_name="workspace_activities")
    op.drop_table("workspace_activities")
    # ### end Alembic commands ###
