"""Add Newsletter Delivery Infrastructure models

Revision ID: d437878f8fc2
Revises: 89bad6d75e48
Create Date: 2026-06-23 13:28:15.331174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd437878f8fc2'
down_revision: Union[str, Sequence[str], None] = '89bad6d75e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_html', sa.String(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_briefings_id'), 'newsletter_briefings', ['id'], unique=False)
    op.create_table('newsletter_campaign_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('bounced_count', sa.Integer(), nullable=False),
    sa.Column('complained_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('open_rate', sa.String(), nullable=False),
    sa.Column('click_rate', sa.String(), nullable=False),
    sa.Column('bounce_rate', sa.String(), nullable=False),
    sa.Column('delivery_rate', sa.String(), nullable=False),
    sa.Column('last_processed_event_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_index(op.f('ix_newsletter_campaign_analytics_id'), 'newsletter_campaign_analytics', ['id'], unique=False)
    op.create_table('newsletter_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_campaigns_briefing_id'), 'newsletter_campaigns', ['briefing_id'], unique=False)
    op.create_index(op.f('ix_newsletter_campaigns_campaign_name'), 'newsletter_campaigns', ['campaign_name'], unique=False)
    op.create_index(op.f('ix_newsletter_campaigns_id'), 'newsletter_campaigns', ['id'], unique=False)
    op.create_table('newsletter_email_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', 'COMPLAINED', 'FAILED', name='emaildeliverystatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_email_deliveries_campaign_id'), 'newsletter_email_deliveries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_newsletter_email_deliveries_id'), 'newsletter_email_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_email_deliveries_provider_message_id'), 'newsletter_email_deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_newsletter_email_deliveries_subscriber_id'), 'newsletter_email_deliveries', ['subscriber_id'], unique=False)
    op.create_table('newsletter_link_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_link_clicks_delivery_id'), 'newsletter_link_clicks', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_newsletter_link_clicks_id'), 'newsletter_link_clicks', ['id'], unique=False)
    op.create_table('newsletter_suppressed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_suppressed_emails_email'), 'newsletter_suppressed_emails', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_suppressed_emails_id'), 'newsletter_suppressed_emails', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_newsletter_suppressed_emails_id'), table_name='newsletter_suppressed_emails')
    op.drop_index(op.f('ix_newsletter_suppressed_emails_email'), table_name='newsletter_suppressed_emails')
    op.drop_table('newsletter_suppressed_emails')
    op.drop_index(op.f('ix_newsletter_link_clicks_id'), table_name='newsletter_link_clicks')
    op.drop_index(op.f('ix_newsletter_link_clicks_delivery_id'), table_name='newsletter_link_clicks')
    op.drop_table('newsletter_link_clicks')
    op.drop_index(op.f('ix_newsletter_email_deliveries_subscriber_id'), table_name='newsletter_email_deliveries')
    op.drop_index(op.f('ix_newsletter_email_deliveries_provider_message_id'), table_name='newsletter_email_deliveries')
    op.drop_index(op.f('ix_newsletter_email_deliveries_id'), table_name='newsletter_email_deliveries')
    op.drop_index(op.f('ix_newsletter_email_deliveries_campaign_id'), table_name='newsletter_email_deliveries')
    op.drop_table('newsletter_email_deliveries')
    op.drop_index(op.f('ix_newsletter_campaigns_id'), table_name='newsletter_campaigns')
    op.drop_index(op.f('ix_newsletter_campaigns_campaign_name'), table_name='newsletter_campaigns')
    op.drop_index(op.f('ix_newsletter_campaigns_briefing_id'), table_name='newsletter_campaigns')
    op.drop_table('newsletter_campaigns')
    op.drop_index(op.f('ix_newsletter_campaign_analytics_id'), table_name='newsletter_campaign_analytics')
    op.drop_table('newsletter_campaign_analytics')
    op.drop_index(op.f('ix_newsletter_briefings_id'), table_name='newsletter_briefings')
    op.drop_table('newsletter_briefings')
    # ### end Alembic commands ###
