"""add_workspace_digests

Revision ID: d71685bc4595
Revises: 4e111cb2473d
Create Date: 2026-06-12 13:54:34.273102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d71685bc4595"
down_revision: str | Sequence[str] | None = "4e111cb2473d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_digests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("since_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("until_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspace_digests_created_at"), "workspace_digests", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspace_digests_id"), "workspace_digests", ["id"], unique=False)
    op.create_index(op.f("ix_workspace_digests_workspace_id"), "workspace_digests", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_digests_workspace_id"), table_name="workspace_digests")
    op.drop_index(op.f("ix_workspace_digests_id"), table_name="workspace_digests")
    op.drop_index(op.f("ix_workspace_digests_created_at"), table_name="workspace_digests")
    op.drop_table("workspace_digests")
    # ### end Alembic commands ###
