"""add updated_at and last_retry_at to raw_articles

Revision ID: e42734bd8082
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 05:32:23.286455

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e42734bd8082"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raw_articles", sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "raw_articles",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_articles", "updated_at")
    op.drop_column("raw_articles", "last_retry_at")
    # ### end Alembic commands ###
