"""add_funnels

Revision ID: e495bfd02d14
Revises: 11d38f12c21a
Create Date: 2026-06-14 22:50:19.684926

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e495bfd02d14'
down_revision: str | Sequence[str] | None = '11d38f12c21a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('time_window_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnels_id'), 'funnels', ['id'], unique=False)
    op.create_index(op.f('ix_funnels_key'), 'funnels', ['key'], unique=True)
    op.create_table('funnel_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('time_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dimension_key', sa.String(length=255), nullable=False),
    sa.Column('total_started', sa.Integer(), nullable=False),
    sa.Column('total_completed', sa.Integer(), nullable=False),
    sa.Column('step_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('dropoff_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_metrics_id'), 'funnel_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_metrics_time_bucket'), 'funnel_metrics', ['time_bucket'], unique=False)
    op.create_table('funnel_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('dimension_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_step_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_states_id'), 'funnel_states', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_states_subject_id'), 'funnel_states', ['subject_id'], unique=False)
    op.create_table('funnel_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_matcher', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_steps_id'), 'funnel_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funnel_steps_id'), table_name='funnel_steps')
    op.drop_table('funnel_steps')
    op.drop_index(op.f('ix_funnel_states_subject_id'), table_name='funnel_states')
    op.drop_index(op.f('ix_funnel_states_id'), table_name='funnel_states')
    op.drop_table('funnel_states')
    op.drop_index(op.f('ix_funnel_metrics_time_bucket'), table_name='funnel_metrics')
    op.drop_index(op.f('ix_funnel_metrics_id'), table_name='funnel_metrics')
    op.drop_table('funnel_metrics')
    op.drop_index(op.f('ix_funnels_key'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_id'), table_name='funnels')
    op.drop_table('funnels')
    # ### end Alembic commands ###
