"""Add StoryAssignmentDecision

Revision ID: e5928b74e96f
Revises: 79cca561ba7d
Create Date: 2026-06-23 13:30:23.389866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5928b74e96f'
down_revision: Union[str, Sequence[str], None] = '79cca561ba7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_assignment_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('candidate_story_id', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_assignment_decisions_article_id'), 'story_assignment_decisions', ['article_id'], unique=False)
    op.create_index(op.f('ix_story_assignment_decisions_candidate_story_id'), 'story_assignment_decisions', ['candidate_story_id'], unique=False)
    op.create_index(op.f('ix_story_assignment_decisions_decided_at'), 'story_assignment_decisions', ['decided_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_assignment_decisions_decided_at'), table_name='story_assignment_decisions')
    op.drop_index(op.f('ix_story_assignment_decisions_candidate_story_id'), table_name='story_assignment_decisions')
    op.drop_index(op.f('ix_story_assignment_decisions_article_id'), table_name='story_assignment_decisions')
    op.drop_table('story_assignment_decisions')
    # ### end Alembic commands ###
