"""Add source and UserInterest

Revision ID: e6bad02e4ff8
Revises: 74a94c2b9b77
Create Date: 2026-06-14 10:15:01.833297

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6bad02e4ff8"
down_revision: str | Sequence[str] | None = "74a94c2b9b77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_interests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("anonymous_id", sa.String(length=255), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_interests_anon_entity", "user_interests", ["anonymous_id", "entity_type", "entity_id"], unique=True
    )
    op.create_index(op.f("ix_user_interests_anonymous_id"), "user_interests", ["anonymous_id"], unique=False)
    op.create_index(op.f("ix_user_interests_id"), "user_interests", ["id"], unique=False)
    op.create_index(
        "ix_user_interests_user_entity", "user_interests", ["user_id", "entity_type", "entity_id"], unique=True
    )
    op.create_index(op.f("ix_user_interests_user_id"), "user_interests", ["user_id"], unique=False)
    op.add_column("behavioral_events", sa.Column("source", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("behavioral_events", "source")
    op.drop_index(op.f("ix_user_interests_user_id"), table_name="user_interests")
    op.drop_index("ix_user_interests_user_entity", table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_id"), table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_anonymous_id"), table_name="user_interests")
    op.drop_index("ix_user_interests_anon_entity", table_name="user_interests")
    op.drop_table("user_interests")
    # ### end Alembic commands ###
