"""add completion rate and deliveries to snapshot

Revision ID: edbc1e93c343
Revises: 4c38685103c2
Create Date: 2026-06-23 14:13:34.837353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbc1e93c343'
down_revision: Union[str, Sequence[str], None] = '4c38685103c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_telemetry_snapshots', sa.Column('avg_completion_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('story_telemetry_snapshots', sa.Column('newsletter_deliveries', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_telemetry_snapshots', 'newsletter_deliveries')
    op.drop_column('story_telemetry_snapshots', 'avg_completion_rate')
    # ### end Alembic commands ###
