"""add vector embeddings

Revision ID: ee9b2cc63fb4
Revises: 5e319a49596e
Create Date: 2026-06-11 12:03:43.969364

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee9b2cc63fb4"
down_revision: str | Sequence[str] | None = "5e319a49596e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column(
        "processed_articles",
        sa.Column("embedding_status", sa.String(length=50), server_default="pending", nullable=False),
    )
    op.add_column(
        "processed_articles", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True)
    )
    op.add_column("processed_articles", sa.Column("embedding_hash", sa.String(length=64), nullable=True))
    op.add_column("processed_articles", sa.Column("embedding_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_processed_articles_embedding_status"), "processed_articles", ["embedding_status"], unique=False
    )

    # Create HNSW index
    op.execute(
        "CREATE INDEX ix_processed_articles_embedding ON processed_articles USING hnsw (embedding vector_cosine_ops);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_processed_articles_embedding;")
    op.drop_index(op.f("ix_processed_articles_embedding_status"), table_name="processed_articles")
    op.drop_column("processed_articles", "embedding_updated_at")
    op.drop_column("processed_articles", "embedding_hash")
    op.drop_column("processed_articles", "embedding")
    op.drop_column("processed_articles", "embedding_status")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
