"""expand_telemetry

Revision ID: f6d13ffc3202
Revises: 7e85566f1d41
Create Date: 2026-06-14 23:35:25.089929

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6d13ffc3202'
down_revision: str | Sequence[str] | None = '7e85566f1d41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_telemetry', sa.Column('tool_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('generation_telemetry', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('generation_telemetry', sa.Column('pipeline_version', sa.String(length=50), nullable=True))
    op.add_column('generation_telemetry', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('generation_telemetry', sa.Column('profile', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_telemetry', 'profile')
    op.drop_column('generation_telemetry', 'prompt_version')
    op.drop_column('generation_telemetry', 'pipeline_version')
    op.drop_column('generation_telemetry', 'retry_count')
    op.drop_column('generation_telemetry', 'tool_count')
    # ### end Alembic commands ###
