"""add reawaken count to telemetry snapshot

Revision ID: fa75a1f4d104
Revises: edbc1e93c343
Create Date: 2026-06-23 14:18:43.306934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa75a1f4d104'
down_revision: Union[str, Sequence[str], None] = 'edbc1e93c343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_telemetry_snapshots', sa.Column('reawaken_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_telemetry_snapshots', 'reawaken_count')
    # ### end Alembic commands ###
