"""add_recipient_infrastructure

Revision ID: fce3cf70a42c
Revises: b19c378bfc76
Create Date: 2026-06-14 19:56:01.131678

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fce3cf70a42c'
down_revision: str | Sequence[str] | None = 'b19c378bfc76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiences_id'), 'audiences', ['id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_subscribers_primary_email'), 'subscribers', ['primary_email'], unique=True)
    op.create_index(op.f('ix_subscribers_user_id'), 'subscribers', ['user_id'], unique=False)
    op.create_table('delivery_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_preferences_id'), 'delivery_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_preferences_subscriber_id'), 'delivery_preferences', ['subscriber_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('preference', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_id'), 'preferences', ['id'], unique=False)
    op.create_index(op.f('ix_preferences_subscriber_id'), 'preferences', ['subscriber_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('compiled_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_audience_id'), 'segments', ['audience_id'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_table('subscriber_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_contacts_id'), 'subscriber_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_subscriber_contacts_subscriber_id'), 'subscriber_contacts', ['subscriber_id'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_id'), 'subscription_events', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_events_subscriber_id'), 'subscription_events', ['subscriber_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_audience_id'), 'subscriptions', ['audience_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_audience_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_events_subscriber_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_id'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index(op.f('ix_subscriber_contacts_subscriber_id'), table_name='subscriber_contacts')
    op.drop_index(op.f('ix_subscriber_contacts_id'), table_name='subscriber_contacts')
    op.drop_table('subscriber_contacts')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_audience_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_preferences_subscriber_id'), table_name='preferences')
    op.drop_index(op.f('ix_preferences_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_delivery_preferences_subscriber_id'), table_name='delivery_preferences')
    op.drop_index(op.f('ix_delivery_preferences_id'), table_name='delivery_preferences')
    op.drop_table('delivery_preferences')
    op.drop_index(op.f('ix_subscribers_user_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_primary_email'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_audiences_id'), table_name='audiences')
    op.drop_table('audiences')
    # ### end Alembic commands ###
