import * as React from "react";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Sparkles, FileText } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface AISummaryProps {
  summary: string;
  provider?: string;
}

export function AISummary({ summary, provider }: AISummaryProps) {
  if (!summary) return null;

  return (
    <Card className="bg-surface/50 border-accent/20 shadow-soft">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium flex items-center gap-2 text-accent">
          <Sparkles className="h-4 w-4" />
          AI Summary
          {provider && (
            <span className="text-xs text-muted-foreground ml-auto font-normal flex items-center">
              Generated by {provider}
            </span>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-foreground/90 leading-relaxed">
          {summary}
        </p>
      </CardContent>
    </Card>
  );
}
