from typing import Any

from app.intelligence.generation.context import AIContext
from app.intelligence.generation.interfaces import OutputValidator


class CitationValidator(OutputValidator):
    """
    Validates that any citation generated by the LLM maps deterministically to the retrieved context.
    """
    def execute(self, response_text: str, context: AIContext) -> dict[str, Any]:
        valid_citations = []
        invalid_citations = []

        context_ids = {c.get("source_id") for c in context.compressed_chunks}

        for cid in context_ids:
            if f"[{cid}]" in response_text:
                valid_citations.append({"id": cid, "status": "VALID"})

        return {
            "valid": valid_citations,
            "invalid": invalid_citations,
            "is_valid": len(invalid_citations) == 0
        }

class OutputValidatorRegistry:
    def __init__(self, validators: list[OutputValidator]):
        self.validators = validators

    def execute_all(self, response_text: str, context: AIContext) -> dict[str, Any]:
        results = {}
        is_valid = True
        for validator in self.validators:
            name = validator.__class__.__name__
            val_res = validator.execute(response_text, context)
            results[name] = val_res
            if not val_res.get("is_valid", True):
                is_valid = False
        return {
            "is_valid": is_valid,
            "details": results
        }
